import assert from "node:assert/strict";
import test from "node:test";

import {
  getFounderProgressForOpportunity,
  getFounderProgressForSignal,
} from "../lib/founder-progress";
import type { ContentOpportunity } from "../lib/content-opportunities";
import type { SignalRecord } from "../types/signal";

function buildSignal(overrides: Partial<SignalRecord> = {}): SignalRecord {
  return {
    recordId: "signal-1",
    sourceTitle: "Signal",
    status: "New",
    createdDate: "2026-03-25T00:00:00.000Z",
    createdBy: null,
    reviewNotes: null,
    reuseFlag: false,
    ingestionSource: null,
    ingestionMethod: null,
    signalRelevanceScore: null,
    signalNoveltyScore: null,
    signalUrgencyScore: null,
    brandFitScore: null,
    sourceTrustScore: null,
    duplicateClusterId: null,
    keepRejectRecommendation: null,
    whySelected: null,
    whyRejected: null,
    autoGenerated: false,
    needsHumanReview: false,
    qualityGateResult: null,
    similarityToExistingContent: null,
    reviewPriority: null,
    scheduledDate: null,
    postedDate: null,
    sourceUrl: null,
    sourceType: null,
    sourcePublisher: null,
    sourceDate: null,
    rawExcerpt: null,
    manualSummary: null,
    scenarioAngle: null,
    signalCategory: null,
    severityScore: null,
    signalSubtype: null,
    emotionalPattern: null,
    teacherPainPoint: null,
    relevanceToZazaDraft: null,
    riskToTeacher: null,
    interpretationNotes: null,
    hookTemplateUsed: null,
    contentAngle: null,
    platformPriority: null,
    suggestedFormatPriority: null,
    xDraft: null,
    linkedInDraft: null,
    redditDraft: null,
    finalXDraft: null,
    finalLinkedInDraft: null,
    finalRedditDraft: null,
    xReviewStatus: null,
    linkedInReviewStatus: null,
    redditReviewStatus: null,
    finalReviewNotes: null,
    finalReviewStartedAt: null,
    finalReviewedAt: null,
    imagePrompt: null,
    videoScript: null,
    ctaOrClosingLine: null,
    hashtagsOrKeywords: null,
    posted: false,
    platformPostedTo: null,
    finalCaptionUsed: null,
    assetLink: null,
    postUrl: null,
    platformPerformedBest: null,
    likesOrReactions: null,
    comments: null,
    sharesOrReposts: null,
    saves: null,
    clicks: null,
    engagementScore: null,
    outcomeQuality: null,
    whyItPerformedOrDidnt: null,
    repeatablePattern: false,
    bestHookSignalCombination: null,
    evergreenPotential: null,
    repurposeLater: false,
    repurposeIdeas: null,
    teacherVoiceSource: null,
    anonymisedUserPattern: null,
    relatedZazaFrameworkTag: null,
    editorialMode: null,
    founderVoiceMode: null,
    founderVoiceAppliedAt: null,
    campaignId: null,
    pillarId: null,
    audienceSegmentId: null,
    funnelStage: null,
    ctaGoal: null,
    generationModelVersion: null,
    promptVersion: null,
    assetBundleJson: null,
    repurposingBundleJson: null,
    publishPrepBundleJson: null,
    selectedRepurposedOutputIdsJson: null,
    autoRepairHistoryJson: null,
    preferredAssetType: null,
    selectedImageAssetId: null,
    selectedVideoConceptId: null,
    generatedImageUrl: null,
    ...overrides,
  };
}

function buildOpportunity(
  overrides: Partial<ContentOpportunity> = {},
): ContentOpportunity {
  return {
    opportunityId: "opportunity-1",
    signalId: "signal-1",
    title: "Opportunity",
    primaryPainPoint: "Pain point",
    status: "approved_for_production",
    founderSelectionStatus: "pending",
    selectedVideoBrief: null,
    generationState: null,
    ...overrides,
  } as ContentOpportunity;
}

test("getFounderProgressForSignal reports interpretation_needs_saving for new signals", () => {
  assert.equal(
    getFounderProgressForSignal(buildSignal({ status: "New" })),
    "interpretation-needs-saving",
  );
});

test("getFounderProgressForSignal reports ready_for_approval after interpretation", () => {
  assert.equal(
    getFounderProgressForSignal(buildSignal({ status: "Interpreted" })),
    "ready-for-approval",
  );
});

test("getFounderProgressForOpportunity reports ready_to_build_brief before founder approval", () => {
  assert.equal(
    getFounderProgressForOpportunity(buildOpportunity()),
    "ready-to-build-brief",
  );
});

test("getFounderProgressForOpportunity reports ready_to_generate once the brief is approved", () => {
  assert.equal(
    getFounderProgressForOpportunity(
      buildOpportunity({
        founderSelectionStatus: "approved",
        selectedVideoBrief: { id: "brief-1" } as ContentOpportunity["selectedVideoBrief"],
      }),
    ),
    "ready-to-generate",
  );
});

test("getFounderProgressForOpportunity reports ready_to_review_render once a render exists", () => {
  assert.equal(
    getFounderProgressForOpportunity(
      buildOpportunity({
        founderSelectionStatus: "approved",
        selectedVideoBrief: { id: "brief-1" } as ContentOpportunity["selectedVideoBrief"],
        generationState: {
          renderedAsset: { id: "asset-1" },
          assetReview: { status: "pending_review" },
        } as ContentOpportunity["generationState"],
      }),
    ),
    "ready-to-review-render",
  );
});
