import assert from "node:assert/strict";
import test from "node:test";

import type { ContentOpportunity } from "../lib/content-opportunities";
import {
  buildVideoFactoryReviewBrief,
  buildVideoFactoryReviewJob,
} from "../lib/video-factory-review-model";

function buildOpportunityFixture(): ContentOpportunity {
  return {
    opportunityId: "opportunity-1",
    signalId: "signal-1",
    title: "Teacher email anxiety",
    opportunityType: "pain_point_opportunity",
    status: "approved_for_production",
    priority: "high",
    source: {
      signalId: "signal-1",
      sourceTitle: "Signal",
      href: "https://example.com",
      clusterId: null,
    },
    primaryPainPoint: "Teachers worry about tone in parent emails.",
    teacherLanguage: ["I always second-guess the send button."],
    recommendedAngle: "Calm reassurance",
    recommendedHookDirection: "empathetic",
    recommendedFormat: "short_video",
    recommendedPlatforms: ["linkedin"],
    whyNow: "Parent comms are peaking.",
    commercialPotential: "high",
    trustRisk: "low",
    riskSummary: null,
    suggestedNextStep: "Generate a video.",
    supportingSignals: [],
    memoryContext: {
      bestCombo: null,
      weakCombo: null,
      revenuePattern: null,
      audienceCue: "Primary and secondary teachers",
      caution: null,
    },
    sourceSignalIds: ["signal-1"],
    createdAt: "2026-03-23T10:00:00.000Z",
    updatedAt: "2026-03-23T10:05:00.000Z",
    approvedAt: "2026-03-23T10:01:00.000Z",
    dismissedAt: null,
    founderSelectionStatus: "approved",
    selectedAngleId: "angle-1",
    selectedHookId: "hook-1",
    selectedVideoBrief: {
      id: "brief-1",
      opportunityId: "opportunity-1",
      angleId: "angle-1",
      hookSetId: "hook-set-1",
      title: "Teachers second-guess every email",
      hook: "Every teacher knows the feeling of rereading the email five times.",
      format: "talking-head",
      durationSec: 30,
      goal: "Drive trials",
      tone: "teacher-real",
      structure: [
        { order: 1, purpose: "problem", guidance: "Email tone is easy to misread." },
        { order: 2, purpose: "solution", guidance: "Zaza Draft flags risky wording." },
        { order: 3, purpose: "reassurance", guidance: "Teachers feel calmer before sending." },
      ],
      visualDirection: "Simple portrait setup.",
      overlayLines: ["Tone check", "Send with confidence"],
      cta: "Try Zaza Draft free.",
      productionNotes: ["No exaggerated claims", "No urgency language"],
    },
    generationState: {
      videoBriefApprovedAt: "2026-03-23T10:02:00.000Z",
      videoBriefApprovedBy: "founder",
      factoryLifecycle: {
        factoryJobId: "factory-job-2",
        videoBriefId: "brief-1",
        provider: "runway",
        renderVersion: "v2",
        status: "review_pending",
        draftAt: "2026-03-23T10:02:00.000Z",
        queuedAt: "2026-03-23T10:03:00.000Z",
        retryQueuedAt: null,
        preparingAt: "2026-03-23T10:03:10.000Z",
        generatingNarrationAt: "2026-03-23T10:03:20.000Z",
        generatingVisualsAt: "2026-03-23T10:03:30.000Z",
        generatingCaptionsAt: "2026-03-23T10:03:40.000Z",
        composingAt: "2026-03-23T10:03:50.000Z",
        generatedAt: "2026-03-23T10:04:00.000Z",
        reviewPendingAt: "2026-03-23T10:04:10.000Z",
        acceptedAt: null,
        rejectedAt: null,
        discardedAt: null,
        failedAt: null,
        failedPermanentAt: null,
        lastUpdatedAt: "2026-03-23T10:04:10.000Z",
        failureStage: null,
        failureMessage: null,
        retryState: null,
      },
      latestCostEstimate: {
        estimatedTotalUsd: 1.24,
        narrationCostUsd: 0.22,
        visualsCostUsd: 0.9,
        transcriptionCostUsd: 0.12,
        compositionCostUsd: 0,
        providerId: "runway-gen4",
        mode: "quality",
        estimatedAt: "2026-03-23T10:03:00.000Z",
      },
      latestActualCost: {
        jobId: "render-2",
        estimatedCostUsd: 1.24,
        actualCostUsd: 1.18,
        narrationActualUsd: 0.18,
        visualsActualUsd: 0.88,
        transcriptActualUsd: 0.12,
        compositionActualUsd: 0,
        providerId: "runway-gen4",
        completedAt: "2026-03-23T10:04:10.000Z",
      },
      latestBudgetGuard: {
        status: "warning",
        estimatedTotalUsd: 1.24,
        warningThresholdUsd: 1,
        hardStopThresholdUsd: 2,
        warningMessage: "Estimated run cost $1.24 exceeds the warning threshold of $1.00.",
        hardStopMessage: null,
        evaluatedAt: "2026-03-23T10:03:00.000Z",
      },
      latestQualityCheck: {
        passed: true,
        hasAudio: true,
        durationSeconds: 30,
        expectedDuration: 30,
        durationInRange: true,
        captionsPresent: true,
        sceneCount: 2,
        failures: [],
        checkedAt: "2026-03-23T10:04:00.000Z",
      },
      latestRetryState: {
        retryCount: 0,
        maxRetries: 2,
        backoffDelayMs: null,
        nextRetryAt: null,
        lastFailureAt: null,
        retryStage: null,
        failureMode: "none",
        exhausted: false,
      },
      runLedger: [
        {
          ledgerEntryId: "ledger-2",
          factoryJobId: "factory-job-2",
          opportunityId: "opportunity-1",
          videoBriefId: "brief-1",
          attemptNumber: 2,
          generationRequestId: "generation-2",
          renderJobId: "render-2",
          renderedAssetId: "asset-2",
          providerSet: {
            renderProvider: "runway",
            narrationProvider: "elevenlabs",
            visualProviders: ["runway-gen4"],
            captionProvider: "assemblyai",
            compositionProvider: "ffmpeg",
          },
          lifecycleTransitions: [
            { status: "queued", at: "2026-03-23T10:03:00.000Z" },
            { status: "review_pending", at: "2026-03-23T10:04:10.000Z" },
          ],
          artifactIds: ["narration-1", "scene-1", "caption-1", "video-1", "thumb-1"],
          estimatedCost: {
            estimatedTotalUsd: 1.24,
            narrationCostUsd: 0.22,
            visualsCostUsd: 0.9,
            transcriptionCostUsd: 0.12,
            compositionCostUsd: 0,
            providerId: "runway-gen4",
            mode: "quality",
            estimatedAt: "2026-03-23T10:03:00.000Z",
          },
          actualCost: {
            jobId: "render-2",
            estimatedCostUsd: 1.24,
            actualCostUsd: 1.18,
            narrationActualUsd: 0.18,
            visualsActualUsd: 0.88,
            transcriptActualUsd: 0.12,
            compositionActualUsd: 0,
            providerId: "runway-gen4",
            completedAt: "2026-03-23T10:04:10.000Z",
          },
          budgetGuard: {
            status: "warning",
            estimatedTotalUsd: 1.24,
            warningThresholdUsd: 1,
            hardStopThresholdUsd: 2,
            warningMessage: "Estimated run cost $1.24 exceeds the warning threshold of $1.00.",
            hardStopMessage: null,
            evaluatedAt: "2026-03-23T10:03:00.000Z",
          },
          terminalOutcome: "review_pending",
          regenerationReasonCodes: ["tone_mismatch"],
          regenerationNotes: "Tone landed slightly too polished.",
          decisionStructuredReasons: [],
          decisionNotes: null,
          lastUpdatedAt: "2026-03-23T10:04:10.000Z",
          failureStage: null,
          failureMessage: null,
          retryState: null,
          qualityCheck: null,
        },
      ],
      comparisonRecords: [],
      attemptLineage: [
        {
          attemptId: "attempt-2",
          factoryJobId: "factory-job-2",
          renderVersion: "v2",
          generationRequestId: "generation-2",
          renderJobId: "render-2",
          renderedAssetId: "asset-2",
          costEstimate: {
            estimatedTotalUsd: 1.24,
            narrationCostUsd: 0.22,
            visualsCostUsd: 0.9,
            transcriptionCostUsd: 0.12,
            compositionCostUsd: 0,
            providerId: "runway-gen4",
            mode: "quality",
            estimatedAt: "2026-03-23T10:03:00.000Z",
          },
          actualCost: {
            jobId: "render-2",
            estimatedCostUsd: 1.24,
            actualCostUsd: 1.18,
            narrationActualUsd: 0.18,
            visualsActualUsd: 0.88,
            transcriptActualUsd: 0.12,
            compositionActualUsd: 0,
            providerId: "runway-gen4",
            completedAt: "2026-03-23T10:04:10.000Z",
          },
          budgetGuard: {
            status: "warning",
            estimatedTotalUsd: 1.24,
            warningThresholdUsd: 1,
            hardStopThresholdUsd: 2,
            warningMessage: "Estimated run cost $1.24 exceeds the warning threshold of $1.00.",
            hardStopMessage: null,
            evaluatedAt: "2026-03-23T10:03:00.000Z",
          },
          qualityCheck: null,
          retryState: null,
          providerExecutions: [],
          narrationArtifact: {
            artifactId: "narration-1",
            artifactType: "narration_audio",
            executionId: "exec-narration-1",
            renderJobId: "render-2",
            renderVersion: "v2",
            narrationSpecId: "narration-spec-1",
            providerId: "elevenlabs",
            audioUrl: "https://blob.example/narration.mp3",
            durationSec: 30,
            storage: {
              backend: "blob",
              pathname: "video-factory/narration.mp3",
              url: "https://blob.example/narration.mp3",
              sourceUrl: "https://source.example/narration.mp3",
              contentType: "audio/mpeg",
              persistedAt: "2026-03-23T10:03:21.000Z",
            },
            createdAt: "2026-03-23T10:03:20.000Z",
          },
          sceneArtifacts: [
            {
              artifactId: "scene-1",
              artifactType: "scene_video",
              executionId: "exec-scene-1",
              renderJobId: "render-2",
              renderVersion: "v2",
              scenePromptId: "scene-prompt-1",
              providerId: "runway-gen4",
              assetUrl: "https://blob.example/scene-1.mp4",
              order: 1,
              storage: null,
              createdAt: "2026-03-23T10:03:31.000Z",
            },
          ],
          captionArtifact: {
            artifactId: "caption-1",
            artifactType: "caption_track",
            executionId: "exec-caption-1",
            renderJobId: "render-2",
            renderVersion: "v2",
            captionSpecId: "caption-spec-1",
            sourceNarrationId: "narration-1",
            providerId: "assemblyai",
            transcriptText: "Transcript",
            captionUrl: "https://blob.example/caption.vtt",
            storage: {
              backend: "blob",
              pathname: "video-factory/caption.vtt",
              url: "https://blob.example/caption.vtt",
              sourceUrl: "https://source.example/caption.vtt",
              contentType: "text/vtt",
              persistedAt: "2026-03-23T10:03:41.000Z",
            },
            createdAt: "2026-03-23T10:03:40.000Z",
          },
          composedVideoArtifact: {
            artifactId: "video-1",
            artifactType: "composed_video",
            executionId: "exec-video-1",
            renderJobId: "render-2",
            renderVersion: "v2",
            compositionSpecId: "composition-spec-1",
            providerId: "ffmpeg",
            videoUrl: "https://blob.example/video.mp4",
            thumbnailUrl: "https://blob.example/thumb.jpg",
            durationSec: 30,
            storage: {
              backend: "blob",
              pathname: "video-factory/video.mp4",
              url: "https://blob.example/video.mp4",
              sourceUrl: "https://source.example/video.mp4",
              contentType: "video/mp4",
              persistedAt: "2026-03-23T10:04:01.000Z",
            },
            createdAt: "2026-03-23T10:04:00.000Z",
          },
          thumbnailArtifact: {
            artifactId: "thumb-1",
            artifactType: "thumbnail_image",
            renderJobId: "render-2",
            renderVersion: "v2",
            providerId: "ffmpeg",
            imageUrl: "https://blob.example/thumb.jpg",
            storage: {
              backend: "blob",
              pathname: "video-factory/thumb.jpg",
              url: "https://blob.example/thumb.jpg",
              sourceUrl: "https://source.example/thumb.jpg",
              contentType: "image/jpeg",
              persistedAt: "2026-03-23T10:04:01.000Z",
            },
            createdAt: "2026-03-23T10:04:00.000Z",
          },
          createdAt: "2026-03-23T10:04:10.000Z",
        },
      ],
      narrationSpec: null,
      videoPrompt: null,
      generationRequest: null,
      renderJob: {
        id: "render-2",
        generationRequestId: "generation-2",
        idempotencyKey: "video-factory:regenerate:opportunity-2:brief-2:v2:runway:none:wrong_mood",
        provider: "runway",
        renderVersion: "v2",
        compiledProductionPlan: null,
        productionDefaultsSnapshot: null,
        providerJobId: "provider-job-2",
        preTriageConcern: "visual_mood_concern",
        regenerationReason: "wrong_mood",
        regenerationReasonCodes: ["tone_mismatch"],
        regenerationNotes: "Wanted a calmer tone.",
        costEstimate: null,
        actualCost: null,
        budgetGuard: null,
        qualityCheck: null,
        retryState: null,
        status: "completed",
        submittedAt: "2026-03-23T10:03:00.000Z",
        completedAt: "2026-03-23T10:04:10.000Z",
        errorMessage: null,
      },
      renderedAsset: {
        id: "asset-2",
        renderJobId: "render-2",
        assetType: "video",
        url: "https://blob.example/video.mp4",
        thumbnailUrl: "https://blob.example/thumb.jpg",
        durationSec: 30,
        createdAt: "2026-03-23T10:04:10.000Z",
      },
      assetReview: {
        id: "review-2",
        renderedAssetId: "asset-2",
        status: "pending_review",
        reviewedAt: null,
        structuredReasons: [],
        reviewNotes: null,
        rejectionReason: null,
      },
      performanceSignals: [],
    },
    operatorNotes: null,
  };
}

test("buildVideoFactoryReviewBrief maps the selected brief", () => {
  const brief = buildVideoFactoryReviewBrief(buildOpportunityFixture());

  assert.equal(brief?.briefId, "brief-1");
  assert.equal(brief?.primaryHook, "Every teacher knows the feeling of rereading the email five times.");
  assert.deepEqual(brief?.trustGuardrails, ["No exaggerated claims", "No urgency language"]);
});

test("buildVideoFactoryReviewJob maps the latest persisted factory attempt", () => {
  const job = buildVideoFactoryReviewJob(buildOpportunityFixture());

  assert.equal(job?.viewState, "review");
  assert.equal(job?.status, "completed");
  assert.equal(job?.currentAttempt, 2);
  assert.equal(job?.priorAttemptsCount, 1);
  assert.equal(job?.retryCount, 0);
  assert.equal(job?.providerLabel, "Narration elevenlabs | Visuals runway-gen4 | Captions assemblyai | Composition ffmpeg");
  assert.equal(job?.qualitySummary, "Passed");
  assert.deepEqual(job?.reviewReasonLabels, []);
  assert.equal(job?.finalVideoUrl, "https://blob.example/video.mp4");
  assert.equal(job?.captionTrackUrl, "https://blob.example/caption.vtt");
  assert.equal(job?.sceneAssetCount, 1);
  assert.equal(job?.actualCostUsd, 1.18);
  assert.equal(job?.steps.composition, "done");
  assert.equal(job?.steps.upload, "done");
});

test("buildVideoFactoryReviewJob keeps the current reviewable attempt when later history exists", () => {
  const opportunity = buildOpportunityFixture();
  opportunity.generationState?.runLedger.push({
    ledgerEntryId: "ledger-3",
    factoryJobId: "factory-job-3",
    opportunityId: "opportunity-1",
    videoBriefId: "brief-1",
    attemptNumber: 3,
    generationRequestId: "generation-3",
    renderJobId: "render-3",
    renderedAssetId: null,
    providerSet: {
      renderProvider: "runway",
      narrationProvider: "elevenlabs",
      visualProviders: ["kling-2"],
      captionProvider: "assemblyai",
      compositionProvider: "ffmpeg",
    },
    lifecycleTransitions: [
      { status: "queued", at: "2026-03-23T10:05:00.000Z" },
      { status: "failed", at: "2026-03-23T10:05:30.000Z" },
    ],
    artifactIds: [],
    estimatedCost: null,
    actualCost: null,
    budgetGuard: null,
    regenerationReasonCodes: [],
    regenerationNotes: null,
    decisionStructuredReasons: [],
    decisionNotes: null,
    terminalOutcome: "failed",
    lastUpdatedAt: "2026-03-23T10:05:30.000Z",
    failureStage: "generating_visuals",
    failureMessage: "Latest attempt failed.",
    retryState: null,
    qualityCheck: null,
  });
  opportunity.generationState?.attemptLineage.push({
    attemptId: "attempt-3",
    factoryJobId: "factory-job-3",
    renderVersion: "v3",
    generationRequestId: "generation-3",
    renderJobId: "render-3",
    renderedAssetId: null,
    costEstimate: {
      estimatedTotalUsd: 1.1,
      narrationCostUsd: 0.2,
      visualsCostUsd: 0.78,
      transcriptionCostUsd: 0.12,
      compositionCostUsd: 0,
      providerId: "kling-2",
      mode: "fast",
      estimatedAt: "2026-03-23T10:05:00.000Z",
    },
    actualCost: null,
    budgetGuard: null,
    qualityCheck: null,
    retryState: null,
    providerExecutions: [],
    narrationArtifact: null,
    sceneArtifacts: [],
    captionArtifact: null,
    composedVideoArtifact: null,
    thumbnailArtifact: null,
    createdAt: "2026-03-23T10:05:30.000Z",
  });

  const job = buildVideoFactoryReviewJob(opportunity);

  assert.equal(job?.currentAttempt, 2);
  assert.equal(job?.priorAttemptsCount, 1);
  assert.equal(job?.retryCount, 0);
  assert.equal(job?.providerLabel, "Narration elevenlabs | Visuals runway-gen4 | Captions assemblyai | Composition ffmpeg");
  assert.equal(job?.finalVideoUrl, "https://blob.example/video.mp4");
  assert.equal(job?.sceneAssetCount, 1);
  assert.equal(job?.terminalOutcome, "review_pending");
});
