import assert from "node:assert/strict";
import test from "node:test";

import type { ContentOpportunity } from "../lib/content-opportunities";
import { buildFactoryRunsObservability } from "../lib/video-factory-runs";

function buildOpportunityFixture(input?: {
  status?: NonNullable<
    NonNullable<ContentOpportunity["generationState"]>["factoryLifecycle"]
  >["status"];
  includeLedger?: boolean;
}) {
  const includeLedger = input?.includeLedger ?? true;
  const lifecycleStatus = input?.status ?? "accepted";

  return {
    opportunityId: "opportunity-1",
    signalId: "signal-1",
    title: "Teacher email tone check",
    opportunityType: "pain_point_opportunity",
    status: "approved_for_production",
    priority: "high",
    source: {
      signalId: "signal-1",
      sourceTitle: "Signal",
      href: "https://example.com",
      clusterId: null,
    },
    primaryPainPoint: "Tone uncertainty before sending parent emails.",
    painPointCategory: null,
    teacherLanguage: ["I keep rereading the message before I send it."],
    recommendedAngle: "Calm reassurance",
    recommendedHookDirection: "empathetic",
    recommendedFormat: "short_video",
    recommendedPlatforms: ["linkedin"],
    whyNow: "High parent message volume.",
    commercialPotential: "high",
    trustRisk: "low",
    riskSummary: null,
    confidence: null,
    historicalCostAvg: null,
    historicalApprovalRate: null,
    suggestedNextStep: "Send to factory.",
    skipReason: null,
    hookOptions: null,
    hookRanking: null,
    performanceDrivers: null,
    intendedViewerEffect: null,
    suggestedCTA: null,
    productionComplexity: null,
    growthIntelligence: null,
    supportingSignals: [],
    memoryContext: {
      bestCombo: null,
      weakCombo: null,
      revenuePattern: null,
      audienceCue: null,
      caution: null,
    },
    sourceSignalIds: ["signal-1"],
    createdAt: "2026-03-23T09:55:00.000Z",
    updatedAt: "2026-03-23T10:10:00.000Z",
    approvedAt: "2026-03-23T10:00:00.000Z",
    dismissedAt: null,
    messageAngles: [],
    hookSets: [],
    founderSelectionStatus: "approved",
    selectedAngleId: "angle-1",
    selectedHookId: "hook-1",
    selectedVideoBrief: {
      id: "brief-1",
      opportunityId: "opportunity-1",
      angleId: "angle-1",
      hookSetId: "hook-set-1",
      title: "Pause before you send it",
      hook: "Before you send this, read it once like a parent would.",
      format: "talking-head",
      durationSec: 30,
      goal: "Drive trials",
      tone: "teacher-real",
      structure: [],
      visualDirection: "Simple portrait shot.",
      overlayLines: [],
      cta: "Try Zaza Draft",
      contentType: null,
      finalScriptTrustScore: 88,
      productionNotes: [],
    },
    generationState: {
      videoBriefApprovedAt: "2026-03-23T10:00:00.000Z",
      videoBriefApprovedBy: "founder",
      factoryLifecycle: {
        factoryJobId: "factory-job-1",
        videoBriefId: "brief-1",
        provider: "runway",
        renderVersion: "phase-c-render-v1",
        status: lifecycleStatus,
        draftAt: "2026-03-23T10:00:00.000Z",
        queuedAt: "2026-03-23T10:00:05.000Z",
        retryQueuedAt: null,
        preparingAt: "2026-03-23T10:00:10.000Z",
        generatingNarrationAt: "2026-03-23T10:00:15.000Z",
        generatingVisualsAt: "2026-03-23T10:00:20.000Z",
        generatingCaptionsAt: "2026-03-23T10:00:25.000Z",
        composingAt: "2026-03-23T10:00:30.000Z",
        generatedAt: "2026-03-23T10:00:35.000Z",
        reviewPendingAt: "2026-03-23T10:00:40.000Z",
        acceptedAt: lifecycleStatus === "accepted" ? "2026-03-23T10:00:50.000Z" : null,
        rejectedAt: null,
        discardedAt: null,
        failedAt: null,
        failedPermanentAt: null,
        lastUpdatedAt: "2026-03-23T10:00:50.000Z",
        failureStage: null,
        failureMessage: null,
        retryState: {
          retryCount: 1,
          maxRetries: 3,
          backoffDelayMs: null,
          nextRetryAt: null,
          lastFailureAt: null,
          retryStage: null,
          failureMode: "none",
          exhausted: false,
        },
      },
      latestCostEstimate: {
        estimatedTotalUsd: 1.12,
        narrationCostUsd: 0.2,
        visualsCostUsd: 0.8,
        transcriptionCostUsd: 0.12,
        compositionCostUsd: 0,
        providerId: "runway-gen4",
        mode: "quality",
        estimatedAt: "2026-03-23T10:00:05.000Z",
      },
      latestActualCost: {
        jobId: "render-job-1",
        estimatedCostUsd: 1.12,
        actualCostUsd: 1.06,
        narrationActualUsd: 0.18,
        visualsActualUsd: 0.76,
        transcriptActualUsd: 0.12,
        compositionActualUsd: 0,
        providerId: "runway-gen4",
        completedAt: "2026-03-23T10:00:50.000Z",
      },
      latestBudgetGuard: null,
      latestQualityCheck: {
        passed: true,
        hasAudio: true,
        durationSeconds: 30,
        expectedDuration: 30,
        durationInRange: true,
        captionsPresent: true,
        sceneCount: 2,
        failures: [],
        checkedAt: "2026-03-23T10:00:40.000Z",
      },
      latestRetryState: {
        retryCount: 1,
        maxRetries: 3,
        backoffDelayMs: null,
        nextRetryAt: null,
        lastFailureAt: null,
        retryStage: null,
        failureMode: "none",
        exhausted: false,
      },
      runLedger: includeLedger
        ? [
            {
              ledgerEntryId: "factory-job-1:attempt:1",
              factoryJobId: "factory-job-1",
              opportunityId: "opportunity-1",
              videoBriefId: "brief-1",
              attemptNumber: 1,
              generationRequestId: "generation-request-1",
              renderJobId: "render-job-1",
              renderedAssetId: "rendered-asset-1",
              providerSet: {
                renderProvider: "runway",
                narrationProvider: "elevenlabs",
                visualProviders: ["runway-gen4"],
                captionProvider: "assemblyai",
                compositionProvider: "ffmpeg",
              },
              lifecycleTransitions: [
                { status: "queued", at: "2026-03-23T10:00:05.000Z" },
                { status: "review_pending", at: "2026-03-23T10:00:40.000Z" },
                { status: "accepted", at: "2026-03-23T10:00:50.000Z" },
              ],
              artifactIds: ["narration-1", "scene-1", "caption-1", "video-1"],
              estimatedCost: {
                estimatedTotalUsd: 1.12,
                narrationCostUsd: 0.2,
                visualsCostUsd: 0.8,
                transcriptionCostUsd: 0.12,
                compositionCostUsd: 0,
                providerId: "runway-gen4",
                mode: "quality",
                estimatedAt: "2026-03-23T10:00:05.000Z",
              },
              actualCost: {
                jobId: "render-job-1",
                estimatedCostUsd: 1.12,
                actualCostUsd: 1.06,
                narrationActualUsd: 0.18,
                visualsActualUsd: 0.76,
                transcriptActualUsd: 0.12,
                compositionActualUsd: 0,
                providerId: "runway-gen4",
                completedAt: "2026-03-23T10:00:50.000Z",
              },
              budgetGuard: null,
              qualityCheck: {
                passed: true,
                hasAudio: true,
                durationSeconds: 30,
                expectedDuration: 30,
                durationInRange: true,
                captionsPresent: true,
                sceneCount: 2,
                failures: [],
                checkedAt: "2026-03-23T10:00:40.000Z",
              },
              retryState: {
                retryCount: 1,
                maxRetries: 3,
                backoffDelayMs: null,
                nextRetryAt: null,
                lastFailureAt: null,
                retryStage: null,
                failureMode: "none",
                exhausted: false,
              },
              regenerationReasonCodes: [],
              regenerationNotes: null,
              decisionStructuredReasons: [],
              decisionNotes: null,
              autonomyPolicyReason: null,
              autonomyPolicyRiskLevel: null,
              growthExecutionPath: "video_factory",
              growthExecutionPriority: 82,
              growthRiskLevel: "low",
              growthReasoning: "High priority and content-ready.",
              terminalOutcome: "accepted",
              finalScriptTrustScore: 88,
              finalScriptTrustStatus: "safe",
              lastUpdatedAt: "2026-03-23T10:00:50.000Z",
              failureStage: null,
              failureMessage: null,
            },
          ]
        : [],
      comparisonRecords: [],
      attemptLineage: [
        {
          attemptId: "render-job-1:attempt-lineage",
          factoryJobId: "factory-job-1",
          renderVersion: "phase-c-render-v1",
          generationRequestId: "generation-request-1",
          renderJobId: "render-job-1",
          renderedAssetId: "rendered-asset-1",
          costEstimate: {
            estimatedTotalUsd: 1.12,
            narrationCostUsd: 0.2,
            visualsCostUsd: 0.8,
            transcriptionCostUsd: 0.12,
            compositionCostUsd: 0,
            providerId: "runway-gen4",
            mode: "quality",
            estimatedAt: "2026-03-23T10:00:05.000Z",
          },
          actualCost: null,
          budgetGuard: null,
          qualityCheck: null,
          retryState: null,
          providerExecutions: [],
          narrationArtifact: {
            artifactId: "narration-1",
            artifactType: "narration_audio",
            executionId: "exec-narration-1",
            renderJobId: "render-job-1",
            renderVersion: "phase-c-render-v1",
            narrationSpecId: "narration-spec-1",
            providerId: "elevenlabs",
            audioUrl: "https://example.com/narration.mp3",
            storage: null,
            durationSec: 30,
            createdAt: "2026-03-23T10:00:15.000Z",
          },
          sceneArtifacts: [
            {
              artifactId: "scene-1",
              artifactType: "scene_video",
              executionId: "exec-scene-1",
              renderJobId: "render-job-1",
              renderVersion: "phase-c-render-v1",
              scenePromptId: "scene-prompt-1",
              providerId: "runway-gen4",
              assetUrl: "https://example.com/scene-1.mp4",
              storage: null,
              order: 1,
              createdAt: "2026-03-23T10:00:20.000Z",
            },
          ],
          captionArtifact: {
            artifactId: "caption-1",
            artifactType: "caption_track",
            executionId: "exec-caption-1",
            renderJobId: "render-job-1",
            renderVersion: "phase-c-render-v1",
            captionSpecId: "caption-spec-1",
            sourceNarrationId: "narration-1",
            providerId: "assemblyai",
            transcriptText: "Transcript",
            captionUrl: "https://example.com/caption.vtt",
            storage: null,
            createdAt: "2026-03-23T10:00:25.000Z",
          },
          composedVideoArtifact: {
            artifactId: "video-1",
            artifactType: "composed_video",
            executionId: "exec-video-1",
            renderJobId: "render-job-1",
            renderVersion: "phase-c-render-v1",
            compositionSpecId: "composition-spec-1",
            providerId: "ffmpeg",
            videoUrl: "https://example.com/video.mp4",
            thumbnailUrl: "https://example.com/video.jpg",
            storage: null,
            durationSec: 30,
            createdAt: "2026-03-23T10:00:35.000Z",
          },
          thumbnailArtifact: {
            artifactId: "thumbnail-1",
            artifactType: "thumbnail_image",
            renderJobId: "render-job-1",
            renderVersion: "phase-c-render-v1",
            providerId: "ffmpeg",
            imageUrl: "https://example.com/video.jpg",
            storage: null,
            createdAt: "2026-03-23T10:00:35.000Z",
          },
          createdAt: "2026-03-23T10:00:50.000Z",
        },
      ],
      narrationSpec: null,
      videoPrompt: null,
      generationRequest: null,
      renderJob: {
        id: "render-job-1",
        batchId: "batch-obs-1",
        generationRequestId: "generation-request-1",
        idempotencyKey: "video-factory:opportunity-1",
        provider: "runway",
        renderVersion: "phase-c-render-v1",
        compiledProductionPlan: {
          id: "compiled-plan-1",
          opportunityId: "opportunity-1",
          videoBriefId: "brief-1",
          defaultsSnapshot: {
            id: "prod-default:teacher-real-core",
            profileId: "prod-default:teacher-real-core",
            version: 3,
            changedAt: "2026-03-23T09:00:00.000Z",
            changedSource: "operator:test",
            changeNote: "Tighter caption defaults.",
            name: "Teacher-Real Core",
            isActive: true,
            voiceProvider: "elevenlabs",
            voiceId: "teacher-real-core-v3",
            voiceSettings: {},
            styleAnchorPrompt: "Teacher-real anchor prompt.",
            referenceImageUrl: null,
            modelFamily: null,
            motionStyle: "Quiet cuts.",
            negativeConstraints: ["No hype"],
            aspectRatio: "9:16",
            resolution: "1080p",
            captionStyle: {
              preset: "teacher-real-clean",
              placement: "lower-third",
              casing: "sentence",
            },
            compositionDefaults: {
              transitionStyle: "gentle-cut",
              musicMode: "none",
            },
            reviewDefaults: {
              requireCaptionCheck: true,
            },
            providerFallbacks: {
              narration: ["elevenlabs"],
              visuals: ["runway-gen4"],
              captions: ["local-default"],
              composition: ["local-default"],
            },
            updatedAt: "2026-03-23T09:00:00.000Z",
          },
          narrationSpec: {
            id: "narration-spec-1",
            opportunityId: "opportunity-1",
            videoBriefId: "brief-1",
            targetDurationSec: 30,
            script: "Narration",
            tone: "teacher-real",
            pace: "steady",
          },
          scenePrompts: [
            {
              id: "scene-prompt-1",
              videoBriefId: "brief-1",
              visualPrompt: "Prompt",
              overlayText: "Overlay",
              order: 1,
              purpose: "hook",
              durationSec: 30,
            },
          ],
          captionSpec: {
            id: "caption-spec-1",
            videoBriefId: "brief-1",
            sourceText: "Caption",
            stylePreset: "teacher-real-clean",
            placement: "lower-third",
            casing: "sentence",
          },
          compositionSpec: {
            id: "composition-spec-1",
            videoBriefId: "brief-1",
            aspectRatio: "9:16",
            resolution: "1080p",
            sceneOrder: ["scene-prompt-1"],
            narrationSpecId: "narration-spec-1",
            captionSpecId: "caption-spec-1",
            transitionStyle: "gentle-cut",
            musicMode: "none",
          },
          trustAssessment: {
            score: 91,
            status: "safe",
            adjusted: false,
            reasons: [],
          },
          finalScriptTrustAssessment: {
            score: 88,
            status: "safe",
            adjusted: false,
            reasons: [],
          },
        },
        productionDefaultsSnapshot: null,
        providerJobId: "provider-job-1",
        preTriageConcern: null,
        regenerationReason: null,
        regenerationReasonCodes: [],
        regenerationNotes: null,
        costEstimate: null,
        actualCost: null,
        budgetGuard: null,
        qualityCheck: null,
        retryState: null,
        status: "completed",
        submittedAt: "2026-03-23T10:00:05.000Z",
        completedAt: "2026-03-23T10:00:50.000Z",
        errorMessage: null,
      },
      renderedAsset: {
        id: "rendered-asset-1",
        renderJobId: "render-job-1",
        assetType: "video",
        url: "https://example.com/video.mp4",
        thumbnailUrl: "https://example.com/video.jpg",
        durationSec: 30,
        createdAt: "2026-03-23T10:00:50.000Z",
      },
      assetReview: {
        id: "asset-review-1",
        renderedAssetId: "rendered-asset-1",
        status: lifecycleStatus === "accepted" ? "accepted" : "pending_review",
        reviewedAt: lifecycleStatus === "accepted" ? "2026-03-23T10:02:00.000Z" : null,
        structuredReasons: [],
        reviewNotes: null,
        rejectionReason: null,
      },
      performanceSignals: [],
    },
    operatorNotes: null,
  } satisfies ContentOpportunity;
}

test("buildFactoryRunsObservability flattens ledger-backed runs with defaults version and artifacts", () => {
  const result = buildFactoryRunsObservability({
    opportunities: [buildOpportunityFixture()],
    generatedAt: "2026-03-23T10:10:00.000Z",
    now: new Date("2026-03-23T11:00:00.000Z"),
  });

  assert.equal(result.runCount, 1);
  assert.equal(result.activeCount, 0);
  assert.equal(result.items[0]?.factoryJobId, "factory-job-1");
  assert.equal(result.items[0]?.batchId, "batch-obs-1");
  assert.equal(result.items[0]?.defaultsProfileId, "prod-default:teacher-real-core");
  assert.equal(result.items[0]?.defaultsVersion, 3);
  assert.equal(result.items[0]?.finalScriptTrustScore, 88);
  assert.equal(result.items[0]?.artifactSummary.hasComposedVideo, true);
  assert.equal(result.items[0]?.reviewOutcome.status, "accepted");
});

test("buildFactoryRunsObservability synthesizes active lifecycle rows when no terminal ledger entry exists", () => {
  const result = buildFactoryRunsObservability({
    opportunities: [
      buildOpportunityFixture({
        status: "generating_visuals",
        includeLedger: false,
      }),
    ],
    generatedAt: "2026-03-23T10:10:00.000Z",
    now: new Date("2026-03-23T11:00:00.000Z"),
  });

  assert.equal(result.runCount, 1);
  assert.equal(result.activeCount, 1);
  assert.equal(result.items[0]?.isActive, true);
  assert.equal(result.items[0]?.lifecycleStatus, "generating_visuals");
  assert.equal(result.items[0]?.retryCount, 1);
  assert.equal(result.items[0]?.terminalOutcome, null);
});
