import assert from "node:assert/strict";
import test from "node:test";

import type { ContentOpportunity } from "../lib/content-opportunities";
import { buildLearningSnapshotFromRecords } from "../lib/learning-loop";
import type { ProductionDefaults } from "../lib/production-defaults";
import { resolveVideoFactoryLearningPolicy } from "../lib/video-factory-learning-policy";

function buildDefaults(version: number, isActive: boolean): ProductionDefaults {
  return {
    id: `prod-default:teacher-real-core:v${version}`,
    profileId: "prod-default:teacher-real-core",
    version,
    changedAt: `2026-03-2${version}T00:00:00.000Z`,
    changedSource: "test",
    changeNote: null,
    name: "Teacher-Real Core",
    isActive,
    voiceProvider: "elevenlabs",
    voiceId: "teacher-real-core-v1",
    voiceSettings: {
      stability: 0.48,
      similarityBoost: 0.72,
      style: 0.14,
      speakerBoost: true,
    },
    styleAnchorPrompt: "Teacher-real",
    referenceImageUrl: null,
    modelFamily: null,
    motionStyle: "Quiet cuts",
    negativeConstraints: ["No hype"],
    aspectRatio: "9:16",
    resolution: "1080p",
    captionStyle: {
      preset: "teacher-real-clean",
      placement: "lower-third",
      casing: "sentence",
    },
    compositionDefaults: {
      transitionStyle: "gentle-cut",
      musicMode: "none",
    },
    reviewDefaults: {
      requireCaptionCheck: true,
    },
    providerFallbacks: {
      narration: ["elevenlabs"],
      visuals: ["runway-gen4", "kling-2"],
      captions: ["local-default"],
      composition: ["local-default"],
    },
    updatedAt: `2026-03-2${version}T00:00:00.000Z`,
  };
}

function buildOpportunityFixture(input: {
  id: string;
  provider: string;
  defaultsVersion: number;
  terminalOutcome: "accepted" | "rejected";
}): ContentOpportunity {
  return {
    opportunityId: input.id,
    signalId: `${input.id}:signal`,
    title: `Opportunity ${input.id}`,
    opportunityType: "pain_point_opportunity",
    status: "approved_for_production",
    priority: "high",
    source: {
      signalId: `${input.id}:signal`,
      sourceTitle: "Signal",
      href: "https://example.com",
      clusterId: null,
    },
    primaryPainPoint: "Teachers second-guess parent messaging.",
    painPointCategory: "parent-communication",
    teacherLanguage: ["I keep rewriting the message before sending it."],
    recommendedAngle: "Calm, teacher-real guidance",
    recommendedHookDirection: "empathetic",
    recommendedFormat: "short_video",
    recommendedPlatforms: ["linkedin"],
    whyNow: "The pattern is surfacing this week.",
    commercialPotential: "high",
    trustRisk: "low",
    riskSummary: null,
    confidence: 0.82,
    historicalCostAvg: 1.15,
    historicalApprovalRate: 0.72,
    suggestedNextStep: "Generate a video.",
    skipReason: null,
    hookOptions: ["Before you send that reply..."],
    hookRanking: [{ hook: "Before you send that reply...", score: 19 }],
    performanceDrivers: {
      hookStrength: 4,
      stakes: 4,
      authenticityFit: 4,
    },
    intendedViewerEffect: "Reduce hesitation before parent replies.",
    suggestedCTA: "Try Zaza Draft",
    productionComplexity: "low",
    growthIntelligence: {
      executionPath: "video_factory",
      executionPriority: 78,
      strategicValue: 74,
      learningValue: 61,
      riskLevel: "low",
      expectedOutcome: "Teacher trials",
    },
    supportingSignals: [],
    memoryContext: {
      bestCombo: null,
      weakCombo: null,
      revenuePattern: null,
      audienceCue: "Teachers managing parent replies",
      caution: null,
    },
    sourceSignalIds: [`${input.id}:signal`],
    createdAt: "2026-03-24T09:00:00.000Z",
    updatedAt: "2026-03-24T09:05:00.000Z",
    approvedAt: "2026-03-24T09:04:00.000Z",
    dismissedAt: null,
    messageAngles: [],
    hookSets: [],
    founderSelectionStatus: "approved",
    selectedAngleId: "angle-1",
    selectedHookId: "hook-1",
    selectedVideoBrief: {
      id: `${input.id}:brief`,
      opportunityId: input.id,
      angleId: "angle-1",
      hookSetId: "hook-set-1",
      title: `Brief ${input.id}`,
      hook: "Before you send that reply...",
      format: "talking-head",
      durationSec: 30,
      goal: "Drive trials",
      tone: "teacher-real",
      structure: [
        { order: 1, purpose: "hook", guidance: "Name the risk." },
        { order: 2, purpose: "recognition", guidance: "Reflect the pressure." },
        { order: 3, purpose: "cta", guidance: "Offer a safer next step." },
      ],
      visualDirection: "Direct-to-camera portrait.",
      overlayLines: ["Pause before sending", "Protect tone"],
      cta: "Try Zaza Draft",
      contentType: "validation",
      finalScriptTrustScore: 91,
      productionNotes: ["No hype"],
    },
    generationState: {
      videoBriefApprovedAt: "2026-03-24T09:10:00.000Z",
      videoBriefApprovedBy: "batch-engine",
      factoryLifecycle: null,
      latestCostEstimate: null,
      latestActualCost: null,
      latestBudgetGuard: null,
      latestQualityCheck: null,
      latestRetryState: null,
      runLedger: [
        {
          ledgerEntryId: `${input.id}:ledger`,
          factoryJobId: `${input.id}:factory-job`,
          opportunityId: input.id,
          videoBriefId: `${input.id}:brief`,
          attemptNumber: 1,
          generationRequestId: `${input.id}:request`,
          renderJobId: `${input.id}:render-job`,
          renderedAssetId: `${input.id}:asset`,
          providerSet: {
            renderProvider: input.provider,
            narrationProvider: "elevenlabs",
            visualProviders: [input.provider],
            captionProvider: "local-default",
            compositionProvider: "ffmpeg",
          },
          lifecycleTransitions: [
            { status: "queued", at: "2026-03-24T09:10:00.000Z" },
            { status: input.terminalOutcome, at: "2026-03-24T09:11:00.000Z" },
          ],
          artifactIds: [],
          estimatedCost: null,
          actualCost: {
            jobId: `${input.id}:factory-job`,
            completedAt: "2026-03-24T09:11:00.000Z",
            narrationActualUsd: 0.1,
            visualsActualUsd: 0.7,
            transcriptActualUsd: 0.05,
            compositionActualUsd: 0,
            actualCostUsd: 0.85,
            estimatedCostUsd: 0.9,
            providerId: input.provider,
          },
          budgetGuard: null,
          qualityCheck: null,
          retryState: null,
          regenerationReasonCodes: [],
          regenerationNotes: null,
          decisionStructuredReasons: [],
          decisionNotes: null,
          autonomyPolicyReason: null,
          autonomyPolicyRiskLevel: null,
          growthExecutionPath: "video_factory",
          growthExecutionPriority: 78,
          growthRiskLevel: "low",
          growthReasoning: null,
          finalScriptTrustScore: 91,
          finalScriptTrustStatus: "safe",
          abTest: null,
          terminalOutcome: input.terminalOutcome,
          lastUpdatedAt: "2026-03-24T09:11:00.000Z",
          failureStage: null,
          failureMessage: null,
        },
      ],
      comparisonRecords: [],
      attemptLineage: [],
      narrationSpec: null,
      videoPrompt: null,
      generationRequest: null,
      renderJob: {
        id: `${input.id}:render-job`,
        batchId: null,
        generationRequestId: `${input.id}:request`,
        idempotencyKey: `${input.id}:key`,
        provider: input.provider as "runway" | "capcut" | "mock",
        renderVersion: "phase-c-render-v1",
        compiledProductionPlan: null,
        productionDefaultsSnapshot: buildDefaults(input.defaultsVersion, input.defaultsVersion === 1),
        providerJobId: null,
        preTriageConcern: null,
        regenerationReason: null,
        regenerationReasonCodes: [],
        regenerationNotes: null,
        costEstimate: null,
        actualCost: null,
        budgetGuard: null,
        qualityCheck: null,
        retryState: null,
        abTest: null,
        status: "completed",
        submittedAt: "2026-03-24T09:10:00.000Z",
        completedAt: "2026-03-24T09:11:00.000Z",
        errorMessage: null,
      },
      renderedAsset: null,
      assetReview: {
        id: `${input.id}:review`,
        renderedAssetId: `${input.id}:asset`,
        status: input.terminalOutcome === "accepted" ? "accepted" : "rejected",
        reviewedAt: "2026-03-24T09:11:00.000Z",
        reviewNotes: null,
        rejectionReason: null,
        structuredReasons: [],
      },
      performanceSignals: [],
    },
    operatorNotes: null,
  };
}

test("resolveVideoFactoryLearningPolicy prefers winning providers and defaults versions", () => {
  const opportunities = [
    buildOpportunityFixture({
      id: "opp-1",
      provider: "runway",
      defaultsVersion: 2,
      terminalOutcome: "accepted",
    }),
    buildOpportunityFixture({
      id: "opp-2",
      provider: "runway",
      defaultsVersion: 2,
      terminalOutcome: "accepted",
    }),
    buildOpportunityFixture({
      id: "opp-3",
      provider: "runway",
      defaultsVersion: 2,
      terminalOutcome: "accepted",
    }),
    buildOpportunityFixture({
      id: "opp-4",
      provider: "capcut",
      defaultsVersion: 1,
      terminalOutcome: "rejected",
    }),
  ];
  const snapshot = buildLearningSnapshotFromRecords([
    {
      learningRecordId: "provider-1",
      inputSignature: "video_factory|provider:runway",
      outcome: "success",
      retries: 0,
      cost: 0.8,
      timestamp: "2026-03-24T10:00:00.000Z",
      inputType: "video_factory",
      stage: "operator_review",
      actionType: "auto_run_video_factory",
      sourceId: "provider-1",
      platform: "linkedin",
      format: "short_video",
      hookType: "risk_warning",
      ctaType: "product",
      provider: "runway",
      executionPath: "video_factory",
      approvalRate: 1,
      completionRate: 1,
      costEfficiency: 2,
    },
    {
      learningRecordId: "provider-2",
      inputSignature: "video_factory|provider:capcut",
      outcome: "rejected",
      retries: 1,
      cost: 1.1,
      timestamp: "2026-03-24T10:05:00.000Z",
      inputType: "video_factory",
      stage: "operator_review",
      actionType: "auto_run_video_factory",
      sourceId: "provider-2",
      platform: "linkedin",
      format: "short_video",
      hookType: "risk_warning",
      ctaType: "product",
      provider: "capcut",
      executionPath: "video_factory",
      approvalRate: 0,
      completionRate: 0,
      costEfficiency: 0.1,
    },
  ]);
  const activeDefaults = buildDefaults(1, true);
  const defaultsV2 = buildDefaults(2, false);

  const decision = resolveVideoFactoryLearningPolicy({
    opportunities,
    brief: opportunities[0].selectedVideoBrief!,
    requestedProvider: null,
    deps: {
      getLatestLearningSnapshot: () => snapshot,
      getActiveProductionDefaults: () => activeDefaults,
      listProductionDefaultVersions: () => [activeDefaults, defaultsV2],
    },
  });

  assert.equal(decision.preferredProvider, "runway");
  assert.equal(decision.defaultsSnapshot.version, 2);
  assert.equal(decision.reasons.length >= 1, true);
});
