export const SIGNAL_STATUSES = [
  "New",
  "Interpreted",
  "Draft Generated",
  "Reviewed",
  "Approved",
  "Scheduled",
  "Posted",
  "Archived",
  "Rejected",
] as const;

export const SIGNAL_CATEGORIES = [
  "Risk",
  "Stress",
  "Conflict",
  "Confusion",
  "Success",
] as const;

export const SEVERITY_SCORES = [1, 2, 3] as const;

export const RELEVANCE_LEVELS = ["High", "Medium", "Low"] as const;

export const PLATFORM_PRIORITIES = [
  "X First",
  "LinkedIn First",
  "Reddit First",
  "Multi-platform",
] as const;

export const SUGGESTED_FORMAT_PRIORITIES = [
  "Text",
  "Image",
  "Video",
  "Carousel",
  "Multi-format",
] as const;

export const OUTCOME_QUALITIES = [
  "High Signal",
  "Moderate Signal",
  "Weak Signal",
  "No Data Yet",
] as const;

export const TEACHER_VOICE_SOURCES = [
  "External Public Signal",
  "Internal User Signal",
  "Founder Observation",
  "Support Pattern",
  "Product Usage Pattern",
] as const;

export const HOOK_TEMPLATES = [
  "This could cost you your job",
  "This sounds fine… but it isn’t",
  "This is what emails look like when you’re exhausted",
  "What this really shows",
  "Quiet risk teachers miss",
  "Statistic with human cost",
  "Before / after rewrite",
  "Other",
] as const;

export const EDITORIAL_MODES = [
  "awareness",
  "risk_warning",
  "helpful_tip",
  "thought_leadership",
  "calm_insight",
  "this_could_happen_to_you",
  "professional_guidance",
  "reassurance_deescalation",
] as const;

export const FOUNDER_VOICE_MODES = [
  "founder_voice_on",
  "founder_voice_off",
] as const;

export const FUNNEL_STAGES = [
  "Awareness",
  "Trust",
  "Consideration",
  "Conversion",
  "Retention",
] as const;

export const CTA_GOALS = [
  "Awareness",
  "Visit site",
  "Sign up",
  "Try product",
  "Share / engage",
] as const;

export const ASSET_PRIMARY_TYPES = ["image", "video", "text_first"] as const;
export const AUTO_REPAIR_TYPES = [
  "scenario_angle_reframe",
  "editorial_mode_shift",
  "pattern_fallback",
  "playbook_supported_reframe",
  "generation_retry",
] as const;
export const AUTO_REPAIR_OUTCOMES = [
  "repaired_promoted",
  "repaired_still_held",
  "not_repairable",
] as const;

export const FINAL_DRAFT_REVIEW_STATUSES = ["ready", "needs_edit", "skip"] as const;

export const INTERPRETATION_CONFIDENCE_LEVELS = ["Low", "Medium", "High"] as const;
export const INTERPRETATION_SOURCES = ["rules", "manual", "ai"] as const;
export const GENERATION_SOURCES = ["anthropic", "openai", "mock", "manual"] as const;
export const KEEP_REJECT_RECOMMENDATIONS = ["Keep", "Review", "Reject"] as const;
export const QUALITY_GATE_RESULTS = ["Pass", "Needs Review", "Fail"] as const;
export const REVIEW_PRIORITIES = ["Low", "Medium", "High", "Urgent"] as const;

export type SignalStatus = (typeof SIGNAL_STATUSES)[number];
export type SignalCategory = (typeof SIGNAL_CATEGORIES)[number];
export type SeverityScore = (typeof SEVERITY_SCORES)[number];
export type RelevanceToZazaDraft = (typeof RELEVANCE_LEVELS)[number];
export type PlatformPriority = (typeof PLATFORM_PRIORITIES)[number];
export type SuggestedFormatPriority = (typeof SUGGESTED_FORMAT_PRIORITIES)[number];
export type OutcomeQuality = (typeof OUTCOME_QUALITIES)[number];
export type TeacherVoiceSource = (typeof TEACHER_VOICE_SOURCES)[number];
export type HookTemplate = (typeof HOOK_TEMPLATES)[number];
export type EditorialMode = (typeof EDITORIAL_MODES)[number];
export type FounderVoiceMode = (typeof FOUNDER_VOICE_MODES)[number];
export type FunnelStage = (typeof FUNNEL_STAGES)[number];
export type CtaGoal = (typeof CTA_GOALS)[number];
export type AssetPrimaryType = (typeof ASSET_PRIMARY_TYPES)[number];
export type AutoRepairType = (typeof AUTO_REPAIR_TYPES)[number];
export type AutoRepairOutcome = (typeof AUTO_REPAIR_OUTCOMES)[number];
export type FinalDraftReviewStatus = (typeof FINAL_DRAFT_REVIEW_STATUSES)[number];
export type InterpretationConfidence = (typeof INTERPRETATION_CONFIDENCE_LEVELS)[number];
export type InterpretationSource = (typeof INTERPRETATION_SOURCES)[number];
export type GenerationSource = (typeof GENERATION_SOURCES)[number];
export type KeepRejectRecommendation = (typeof KEEP_REJECT_RECOMMENDATIONS)[number];
export type QualityGateResult = (typeof QUALITY_GATE_RESULTS)[number];
export type ReviewPriority = (typeof REVIEW_PRIORITIES)[number];

export interface SignalCreatePayload {
  createdBy?: string | null;
  sourceUrl: string | null;
  sourceTitle: string;
  sourceType: string | null;
  sourcePublisher: string | null;
  sourceDate: string | null;
  rawExcerpt: string | null;
  manualSummary: string | null;
  scenarioAngle?: string | null;
  signalCategory: SignalCategory | null;
  severityScore: SeverityScore | null;
  hookTemplateUsed: string | null;
  ingestionSource?: string | null;
  ingestionMethod?: string | null;
  keepRejectRecommendation?: KeepRejectRecommendation | null;
  whySelected?: string | null;
  autoGenerated?: boolean | null;
  needsHumanReview?: boolean | null;
  reviewPriority?: ReviewPriority | null;
  campaignId?: string | null;
  pillarId?: string | null;
  audienceSegmentId?: string | null;
  funnelStage?: FunnelStage | null;
  ctaGoal?: CtaGoal | null;
  status: SignalStatus;
}

export interface SignalInterpretationInput {
  recordId?: string;
  sourceTitle: string;
  sourceType: string | null;
  sourcePublisher: string | null;
  sourceDate: string | null;
  sourceUrl: string | null;
  rawExcerpt: string | null;
  manualSummary: string | null;
  scenarioAngle: string | null;
}

export interface SignalInterpretationResult {
  signalCategory: SignalCategory;
  severityScore: SeverityScore;
  signalSubtype: string;
  emotionalPattern: string;
  teacherPainPoint: string;
  relevanceToZazaDraft: RelevanceToZazaDraft;
  riskToTeacher: string;
  interpretationNotes: string;
  hookTemplateUsed: HookTemplate;
  contentAngle: string;
  platformPriority: PlatformPriority;
  suggestedFormatPriority: SuggestedFormatPriority;
  interpretationConfidence: InterpretationConfidence;
  interpretationSource: InterpretationSource;
  interpretedAt: string;
}

export interface SignalInterpretationSavePayload extends SignalInterpretationResult {
  scenarioAngle?: string | null;
  campaignId?: string | null;
  pillarId?: string | null;
  audienceSegmentId?: string | null;
  funnelStage?: FunnelStage | null;
  ctaGoal?: CtaGoal | null;
  status?: SignalStatus;
}

export interface SignalGenerationInput extends SignalInterpretationInput {
  signalCategory: SignalCategory;
  severityScore: SeverityScore;
  signalSubtype: string;
  emotionalPattern: string;
  teacherPainPoint: string;
  relevanceToZazaDraft: RelevanceToZazaDraft;
  riskToTeacher: string;
  interpretationNotes: string;
  hookTemplateUsed: HookTemplate;
  contentAngle: string;
  platformPriority: PlatformPriority;
  suggestedFormatPriority: SuggestedFormatPriority;
}

export interface SignalGenerationResult {
  xDraft: string;
  linkedInDraft: string;
  redditDraft: string;
  imagePrompt: string;
  videoScript: string;
  ctaOrClosingLine: string;
  hashtagsOrKeywords: string;
  assetBundleJson?: string | null;
  repurposingBundleJson?: string | null;
  publishPrepBundleJson?: string | null;
  selectedRepurposedOutputIdsJson?: string | null;
  preferredAssetType?: AssetPrimaryType | null;
  selectedImageAssetId?: string | null;
  selectedVideoConceptId?: string | null;
  generatedImageUrl?: string | null;
  generationSource: GenerationSource;
  generationModelVersion: string;
  promptVersion: string;
  generatedAt: string;
}

export interface SignalGenerationSavePayload extends SignalGenerationResult {
  editorialMode: EditorialMode;
  founderVoiceMode: FounderVoiceMode;
  founderVoiceAppliedAt?: string | null;
  campaignId?: string | null;
  pillarId?: string | null;
  audienceSegmentId?: string | null;
  funnelStage?: FunnelStage | null;
  ctaGoal?: CtaGoal | null;
  status?: SignalStatus;
}

export interface SignalWorkflowUpdatePayload {
  status: SignalStatus;
  scheduledDate?: string | null;
  postedDate?: string | null;
  platformPostedTo?: string | null;
  postUrl?: string | null;
  finalCaptionUsed?: string | null;
  reviewNotes?: string | null;
}

export interface SignalFinalReviewSavePayload {
  finalXDraft: string | null;
  finalLinkedInDraft: string | null;
  finalRedditDraft: string | null;
  xReviewStatus: FinalDraftReviewStatus | null;
  linkedInReviewStatus: FinalDraftReviewStatus | null;
  redditReviewStatus: FinalDraftReviewStatus | null;
  finalReviewNotes: string | null;
  imagePrompt?: string | null;
  videoScript?: string | null;
  assetBundleJson?: string | null;
  repurposingBundleJson?: string | null;
  publishPrepBundleJson?: string | null;
  selectedRepurposedOutputIdsJson?: string | null;
  preferredAssetType?: AssetPrimaryType | null;
  selectedImageAssetId?: string | null;
  selectedVideoConceptId?: string | null;
  generatedImageUrl?: string | null;
  evergreenCandidateId?: string | null;
  appliedEditSuggestions?: Array<{
    key: string;
    platform: "x" | "linkedin" | "reddit";
    patternType: "shortened_hook" | "softened_tone" | "removed_claim" | "changed_cta";
    label: string;
  }>;
  appliedReviewMacros?: Array<{
    macroId: "approve_keep_package" | "approve_soften_cta" | "hold_for_destination_fix" | "convert_to_experiment" | "evergreen_later" | "approve_with_safe_tone";
    platform: "x" | "linkedin" | "reddit";
    appliedAt: string;
  }>;
  founderVoiceMode?: FounderVoiceMode | null;
  founderVoiceAppliedAt?: string | null;
  finalReviewStartedAt?: string | null;
  finalReviewedAt?: string | null;
}

export interface SignalScoringResult {
  signalRelevanceScore: number;
  signalNoveltyScore: number;
  signalUrgencyScore: number;
  brandFitScore: number;
  sourceTrustScore: number;
  keepRejectRecommendation: KeepRejectRecommendation;
  whySelected: string | null;
  whyRejected: string | null;
  needsHumanReview: boolean;
  qualityGateResult: QualityGateResult;
  reviewPriority: ReviewPriority;
  similarityToExistingContent: number | null;
  duplicateClusterId: string | null;
  scoringVersion: string;
  scoredAt: string;
}

export type SignalScoringSavePayload = SignalScoringResult;

export interface SignalAutomationEvaluationFields {
  ingestionSource: string | null;
  ingestionMethod: string | null;
  signalRelevanceScore: number | null;
  signalNoveltyScore: number | null;
  signalUrgencyScore: number | null;
  brandFitScore: number | null;
  sourceTrustScore: number | null;
  duplicateClusterId: string | null;
  keepRejectRecommendation: KeepRejectRecommendation | null;
  whySelected: string | null;
  whyRejected: string | null;
  autoGenerated: boolean | null;
  needsHumanReview: boolean | null;
  qualityGateResult: QualityGateResult | null;
  similarityToExistingContent: number | null;
  reviewPriority: ReviewPriority | null;
}

export interface SignalRecord extends SignalAutomationEvaluationFields {
  recordId: string;
  createdDate: string;
  createdBy: string | null;
  status: SignalStatus;
  reviewNotes: string | null;
  reuseFlag: boolean;
  scheduledDate: string | null;
  postedDate: string | null;
  sourceUrl: string | null;
  sourceTitle: string;
  sourceType: string | null;
  sourcePublisher: string | null;
  sourceDate: string | null;
  rawExcerpt: string | null;
  manualSummary: string | null;
  scenarioAngle: string | null;
  signalCategory: SignalCategory | null;
  severityScore: SeverityScore | null;
  signalSubtype: string | null;
  emotionalPattern: string | null;
  teacherPainPoint: string | null;
  relevanceToZazaDraft: RelevanceToZazaDraft | null;
  riskToTeacher: string | null;
  interpretationNotes: string | null;
  hookTemplateUsed: string | null;
  contentAngle: string | null;
  platformPriority: PlatformPriority | null;
  suggestedFormatPriority: SuggestedFormatPriority | null;
  xDraft: string | null;
  linkedInDraft: string | null;
  redditDraft: string | null;
  finalXDraft: string | null;
  finalLinkedInDraft: string | null;
  finalRedditDraft: string | null;
  xReviewStatus: FinalDraftReviewStatus | null;
  linkedInReviewStatus: FinalDraftReviewStatus | null;
  redditReviewStatus: FinalDraftReviewStatus | null;
  finalReviewNotes: string | null;
  finalReviewStartedAt: string | null;
  finalReviewedAt: string | null;
  imagePrompt: string | null;
  videoScript: string | null;
  ctaOrClosingLine: string | null;
  hashtagsOrKeywords: string | null;
  posted: boolean;
  platformPostedTo: string | null;
  finalCaptionUsed: string | null;
  assetLink: string | null;
  postUrl: string | null;
  platformPerformedBest: string | null;
  likesOrReactions: number | null;
  comments: number | null;
  sharesOrReposts: number | null;
  saves: number | null;
  clicks: number | null;
  engagementScore: number | null;
  outcomeQuality: OutcomeQuality | null;
  whyItPerformedOrDidnt: string | null;
  repeatablePattern: boolean | null;
  bestHookSignalCombination: string | null;
  evergreenPotential: string | null;
  repurposeLater: boolean;
  repurposeIdeas: string | null;
  teacherVoiceSource: TeacherVoiceSource | null;
  anonymisedUserPattern: boolean | null;
  relatedZazaFrameworkTag: string | null;
  editorialMode: EditorialMode | null;
  founderVoiceMode: FounderVoiceMode | null;
  founderVoiceAppliedAt: string | null;
  campaignId: string | null;
  pillarId: string | null;
  audienceSegmentId: string | null;
  funnelStage: FunnelStage | null;
  ctaGoal: CtaGoal | null;
  generationModelVersion: string | null;
  promptVersion: string | null;
  assetBundleJson: string | null;
  repurposingBundleJson: string | null;
  publishPrepBundleJson: string | null;
  selectedRepurposedOutputIdsJson: string | null;
  autoRepairHistoryJson: string | null;
  preferredAssetType: AssetPrimaryType | null;
  selectedImageAssetId: string | null;
  selectedVideoConceptId: string | null;
  generatedImageUrl: string | null;
}

export type UpdateSignalInput = Partial<Omit<SignalRecord, "recordId">>;

export type SignalDataSource = "airtable" | "mock";
