import type { SignalRecord, SignalSubmissionInput } from "@/types/signal";

function createSignalRecord(
  overrides: Partial<SignalRecord> & Pick<SignalRecord, "recordId" | "sourceTitle">,
): SignalRecord {
  return {
    recordId: overrides.recordId,
    createdDate: overrides.createdDate ?? new Date().toISOString(),
    createdBy: overrides.createdBy ?? "Ops Desk",
    status: overrides.status ?? "New",
    reviewNotes: overrides.reviewNotes ?? null,
    reuseFlag: overrides.reuseFlag ?? false,
    scheduledDate: overrides.scheduledDate ?? null,
    postedDate: overrides.postedDate ?? null,
    sourceUrl: overrides.sourceUrl ?? null,
    sourceTitle: overrides.sourceTitle,
    sourceType: overrides.sourceType ?? "Article",
    sourcePublisher: overrides.sourcePublisher ?? null,
    sourceDate: overrides.sourceDate ?? null,
    rawExcerpt: overrides.rawExcerpt ?? null,
    manualSummary: overrides.manualSummary ?? null,
    signalCategory: overrides.signalCategory ?? null,
    severityScore: overrides.severityScore ?? null,
    signalSubtype: overrides.signalSubtype ?? null,
    emotionalPattern: overrides.emotionalPattern ?? null,
    teacherPainPoint: overrides.teacherPainPoint ?? null,
    relevanceToZazaDraft: overrides.relevanceToZazaDraft ?? null,
    riskToTeacher: overrides.riskToTeacher ?? null,
    interpretationNotes: overrides.interpretationNotes ?? null,
    hookTemplateUsed: overrides.hookTemplateUsed ?? null,
    contentAngle: overrides.contentAngle ?? null,
    platformPriority: overrides.platformPriority ?? null,
    suggestedFormatPriority: overrides.suggestedFormatPriority ?? null,
    xDraft: overrides.xDraft ?? null,
    linkedInDraft: overrides.linkedInDraft ?? null,
    redditDraft: overrides.redditDraft ?? null,
    imagePrompt: overrides.imagePrompt ?? null,
    videoScript: overrides.videoScript ?? null,
    ctaOrClosingLine: overrides.ctaOrClosingLine ?? null,
    hashtagsOrKeywords: overrides.hashtagsOrKeywords ?? null,
    posted: overrides.posted ?? false,
    platformPostedTo: overrides.platformPostedTo ?? null,
    finalCaptionUsed: overrides.finalCaptionUsed ?? null,
    assetLink: overrides.assetLink ?? null,
    postUrl: overrides.postUrl ?? null,
    platformPerformedBest: overrides.platformPerformedBest ?? null,
    likesOrReactions: overrides.likesOrReactions ?? null,
    comments: overrides.comments ?? null,
    sharesOrReposts: overrides.sharesOrReposts ?? null,
    saves: overrides.saves ?? null,
    clicks: overrides.clicks ?? null,
    engagementScore: overrides.engagementScore ?? null,
    outcomeQuality: overrides.outcomeQuality ?? "No Data Yet",
    whyItPerformedOrDidnt: overrides.whyItPerformedOrDidnt ?? null,
    repeatablePattern: overrides.repeatablePattern ?? null,
    bestHookSignalCombination: overrides.bestHookSignalCombination ?? null,
    evergreenPotential: overrides.evergreenPotential ?? null,
    repurposeLater: overrides.repurposeLater ?? false,
    repurposeIdeas: overrides.repurposeIdeas ?? null,
    teacherVoiceSource: overrides.teacherVoiceSource ?? null,
    anonymisedUserPattern: overrides.anonymisedUserPattern ?? null,
    relatedZazaFrameworkTag: overrides.relatedZazaFrameworkTag ?? null,
    generationModelVersion: overrides.generationModelVersion ?? null,
    promptVersion: overrides.promptVersion ?? null,
  };
}

export const mockSignalRecords: SignalRecord[] = [
  createSignalRecord({
    recordId: "mock_sig_001",
    createdDate: "2026-03-18T07:30:00.000Z",
    sourceTitle: "Teachers keep rewriting weekly lesson plans because class energy shifts daily",
    sourceUrl: "https://example.com/teacher-routine-shift",
    sourcePublisher: "Founder Notes",
    sourceType: "Internal Note",
    sourceDate: "2026-03-17",
    rawExcerpt:
      "I spent more time adjusting the tone of the lesson than building it. The kids were checked out before I even started.",
    manualSummary: "Signal suggests stress around adapting lesson energy in real time.",
    signalCategory: "Stress",
    severityScore: 2,
    teacherPainPoint: "Teachers are carrying live classroom energy management alone.",
    relevanceToZazaDraft: "High",
    interpretationNotes: "Good candidate for operator-facing content about reducing prep drag.",
    hookTemplateUsed: "Name the hidden friction",
    contentAngle: "The lesson plan is not the problem. Energy mismatch is.",
    platformPriority: "LinkedIn First",
    suggestedFormatPriority: "Text",
    status: "Interpreted",
    teacherVoiceSource: "Founder Observation",
  }),
  createSignalRecord({
    recordId: "mock_sig_002",
    createdDate: "2026-03-18T06:10:00.000Z",
    sourceTitle: "District support thread on parent expectations and after-hours messaging",
    sourceType: "Community Thread",
    sourcePublisher: "Teacher Community",
    rawExcerpt:
      "Parents expect immediate answers, and the emotional labor does not stop when the school day ends.",
    manualSummary: "Boundary erosion theme with strong emotional load.",
    signalCategory: "Conflict",
    severityScore: 3,
    riskToTeacher: "Burnout risk through persistent boundary collapse.",
    relevanceToZazaDraft: "High",
    hookTemplateUsed: "Expose the silent cost",
    platformPriority: "X First",
    suggestedFormatPriority: "Carousel",
    status: "Draft Generated",
    xDraft: "Teachers are not just writing lesson plans. They are carrying an always-on expectation system.",
    linkedInDraft:
      "One of the clearest teacher signals right now is not workload alone. It is the expectation that care must stay available after hours.",
    redditDraft:
      "Seeing a pattern where the teaching day ends but the emotional support queue does not. That is not a small workflow issue.",
    imagePrompt: "Editorial style illustration of a teacher managing a desk stacked with after-hours messages.",
    videoScript: "Hook: The school day ended, but the expectations did not.",
    teacherVoiceSource: "External Public Signal",
  }),
  createSignalRecord({
    recordId: "mock_sig_003",
    createdDate: "2026-03-17T18:15:00.000Z",
    sourceTitle: "Support pattern: new users asking for easier first-week structure",
    sourceType: "Support Ticket",
    sourcePublisher: "Support Inbox",
    manualSummary: "Newer users want faster onboarding into a reliable planning rhythm.",
    signalCategory: "Confusion",
    severityScore: 1,
    relevanceToZazaDraft: "Medium",
    hookTemplateUsed: "Reframe the tension",
    platformPriority: "Multi-platform",
    suggestedFormatPriority: "Text",
    status: "Reviewed",
    reviewNotes: "Useful but needs tighter teacher language before publishing.",
    teacherVoiceSource: "Support Pattern",
  }),
  createSignalRecord({
    recordId: "mock_sig_004",
    createdDate: "2026-03-16T13:40:00.000Z",
    sourceTitle: "Teachers celebrating smoother weekly planning when routines become reusable",
    sourceType: "Article",
    sourcePublisher: "Teacher Newsletter",
    manualSummary: "Positive success signal around reusable systems reducing cognitive load.",
    signalCategory: "Success",
    severityScore: 1,
    relevanceToZazaDraft: "High",
    hookTemplateUsed: "Show the quiet win",
    platformPriority: "LinkedIn First",
    suggestedFormatPriority: "Image",
    status: "Approved",
    reviewNotes: "Approved for repurposing into a practical founder post.",
    teacherVoiceSource: "External Public Signal",
    repurposeLater: true,
    repurposeIdeas: "Turn into a side-by-side visual: reactive planning vs reusable structure.",
  }),
  createSignalRecord({
    recordId: "mock_sig_005",
    createdDate: "2026-03-15T10:05:00.000Z",
    sourceTitle: "Operator note on signals ready for next week scheduling",
    sourceType: "Internal Note",
    sourcePublisher: "Editorial Queue",
    manualSummary: "Scheduled content batch for Tuesday and Thursday.",
    signalCategory: "Risk",
    severityScore: 2,
    relevanceToZazaDraft: "Medium",
    hookTemplateUsed: "Name the preventable cost",
    platformPriority: "X First",
    suggestedFormatPriority: "Text",
    status: "Scheduled",
    scheduledDate: "2026-03-24T08:00:00.000Z",
    teacherVoiceSource: "Internal User Signal",
  }),
];

export function buildMockCreatedSignal(input: SignalSubmissionInput): SignalRecord {
  return createSignalRecord({
    recordId: `mock_sig_${Date.now()}`,
    createdDate: new Date().toISOString(),
    sourceTitle: input.sourceTitle,
    sourceUrl: input.sourceUrl ?? null,
    sourceType: input.sourceType ?? "Other",
    sourcePublisher: input.sourcePublisher ?? "Manual Intake",
    sourceDate: input.sourceDate ?? null,
    rawExcerpt: input.rawExcerpt ?? null,
    manualSummary: input.manualSummary ?? null,
    signalCategory: input.signalCategory ?? null,
    severityScore: input.severityScore ?? null,
    hookTemplateUsed: input.hookTemplateUsed ?? null,
    status: input.status ?? "New",
    createdBy: "Mock Operator",
  });
}
