import type {
  SignalDraft,
  SignalEnvelope,
  SignalEnvelopeMeta,
  SignalInput,
  SignalInterpretation,
  SignalPerformance,
  SignalPublish,
  SignalRecord,
  SignalReview,
  SignalScore,
} from "@/types/signal";

export type SignalEnvelopeLike = SignalEnvelope | SignalRecord;

export function isSignalEnvelope(signal: SignalEnvelopeLike): signal is SignalEnvelope {
  return "meta" in signal && "input" in signal && "score" in signal;
}

export function toSignalEnvelope(signal: SignalEnvelopeLike): SignalEnvelope {
  if (isSignalEnvelope(signal)) {
    return signal;
  }

  const meta: SignalEnvelopeMeta = {
    recordId: signal.recordId,
    createdDate: signal.createdDate,
    createdBy: signal.createdBy,
    status: signal.status,
  };

  const input: SignalInput = {
    sourceUrl: signal.sourceUrl,
    sourceTitle: signal.sourceTitle,
    sourceType: signal.sourceType,
    sourcePublisher: signal.sourcePublisher,
    sourceDate: signal.sourceDate,
    rawExcerpt: signal.rawExcerpt,
    manualSummary: signal.manualSummary,
    scenarioAngle: signal.scenarioAngle,
    ingestionSource: signal.ingestionSource,
    ingestionMethod: signal.ingestionMethod,
    teacherVoiceSource: signal.teacherVoiceSource,
    anonymisedUserPattern: signal.anonymisedUserPattern,
    relatedZazaFrameworkTag: signal.relatedZazaFrameworkTag,
    campaignId: signal.campaignId,
    pillarId: signal.pillarId,
    audienceSegmentId: signal.audienceSegmentId,
    funnelStage: signal.funnelStage,
    ctaGoal: signal.ctaGoal,
  };

  const score: SignalScore = {
    ingestionSource: signal.ingestionSource,
    ingestionMethod: signal.ingestionMethod,
    signalRelevanceScore: signal.signalRelevanceScore,
    signalNoveltyScore: signal.signalNoveltyScore,
    signalUrgencyScore: signal.signalUrgencyScore,
    brandFitScore: signal.brandFitScore,
    sourceTrustScore: signal.sourceTrustScore,
    duplicateClusterId: signal.duplicateClusterId,
    keepRejectRecommendation: signal.keepRejectRecommendation,
    whySelected: signal.whySelected,
    whyRejected: signal.whyRejected,
    autoGenerated: signal.autoGenerated,
    needsHumanReview: signal.needsHumanReview,
    qualityGateResult: signal.qualityGateResult,
    similarityToExistingContent: signal.similarityToExistingContent,
    reviewPriority: signal.reviewPriority,
  };

  const interpretation: SignalInterpretation = {
    signalCategory: signal.signalCategory,
    severityScore: signal.severityScore,
    signalSubtype: signal.signalSubtype,
    emotionalPattern: signal.emotionalPattern,
    teacherPainPoint: signal.teacherPainPoint,
    relevanceToZazaDraft: signal.relevanceToZazaDraft,
    riskToTeacher: signal.riskToTeacher,
    interpretationNotes: signal.interpretationNotes,
    hookTemplateUsed: signal.hookTemplateUsed,
    contentAngle: signal.contentAngle,
    platformPriority: signal.platformPriority,
    suggestedFormatPriority: signal.suggestedFormatPriority,
    campaignId: signal.campaignId,
    pillarId: signal.pillarId,
    audienceSegmentId: signal.audienceSegmentId,
    funnelStage: signal.funnelStage,
    ctaGoal: signal.ctaGoal,
  };

  const draft: SignalDraft = {
    xDraft: signal.xDraft,
    linkedInDraft: signal.linkedInDraft,
    redditDraft: signal.redditDraft,
    imagePrompt: signal.imagePrompt,
    videoScript: signal.videoScript,
    ctaOrClosingLine: signal.ctaOrClosingLine,
    hashtagsOrKeywords: signal.hashtagsOrKeywords,
    editorialMode: signal.editorialMode,
    founderVoiceMode: signal.founderVoiceMode,
    founderVoiceAppliedAt: signal.founderVoiceAppliedAt,
    generationModelVersion: signal.generationModelVersion,
    promptVersion: signal.promptVersion,
    assetBundleJson: signal.assetBundleJson,
    repurposingBundleJson: signal.repurposingBundleJson,
    publishPrepBundleJson: signal.publishPrepBundleJson,
    selectedRepurposedOutputIdsJson: signal.selectedRepurposedOutputIdsJson,
    preferredAssetType: signal.preferredAssetType,
    selectedImageAssetId: signal.selectedImageAssetId,
    selectedVideoConceptId: signal.selectedVideoConceptId,
    generatedImageUrl: signal.generatedImageUrl,
  };

  const review: SignalReview = {
    reviewNotes: signal.reviewNotes,
    finalXDraft: signal.finalXDraft,
    finalLinkedInDraft: signal.finalLinkedInDraft,
    finalRedditDraft: signal.finalRedditDraft,
    xReviewStatus: signal.xReviewStatus,
    linkedInReviewStatus: signal.linkedInReviewStatus,
    redditReviewStatus: signal.redditReviewStatus,
    finalReviewNotes: signal.finalReviewNotes,
    finalReviewStartedAt: signal.finalReviewStartedAt,
    finalReviewedAt: signal.finalReviewedAt,
    autoRepairHistoryJson: signal.autoRepairHistoryJson,
  };

  const publish: SignalPublish = {
    reuseFlag: signal.reuseFlag,
    scheduledDate: signal.scheduledDate,
    postedDate: signal.postedDate,
    posted: signal.posted,
    platformPostedTo: signal.platformPostedTo,
    finalCaptionUsed: signal.finalCaptionUsed,
    assetLink: signal.assetLink,
    postUrl: signal.postUrl,
  };

  const performance: SignalPerformance = {
    platformPerformedBest: signal.platformPerformedBest,
    likesOrReactions: signal.likesOrReactions,
    comments: signal.comments,
    sharesOrReposts: signal.sharesOrReposts,
    saves: signal.saves,
    clicks: signal.clicks,
    engagementScore: signal.engagementScore,
    outcomeQuality: signal.outcomeQuality,
    whyItPerformedOrDidnt: signal.whyItPerformedOrDidnt,
    repeatablePattern: signal.repeatablePattern,
    bestHookSignalCombination: signal.bestHookSignalCombination,
    evergreenPotential: signal.evergreenPotential,
    repurposeLater: signal.repurposeLater,
    repurposeIdeas: signal.repurposeIdeas,
  };

  return {
    meta,
    input,
    score,
    interpretation,
    draft,
    review,
    publish,
    performance,
  };
}

export function flattenSignalEnvelope(signal: SignalEnvelopeLike): SignalRecord {
  if (!isSignalEnvelope(signal)) {
    return signal;
  }

  return {
    ...signal.meta,
    ...signal.input,
    ...signal.score,
    ...signal.interpretation,
    ...signal.draft,
    ...signal.review,
    ...signal.publish,
    ...signal.performance,
  };
}
