import { generateDrafts, toGenerationInputFromSignal } from "@/lib/generator";
import { interpretSignal } from "@/lib/interpreter";
import { createSignal, saveSignalWithFallback } from "@/lib/signal-repository";
import type { FounderVoiceMode } from "@/types/signal";

const TEST_SIGNAL_EDITORIAL_MODE = "reassurance_deescalation";
const TEST_SIGNAL_FOUNDER_VOICE_MODE: FounderVoiceMode = "founder_voice_on";

function buildTestSignalCreatePayload(timestamp: string) {
  return {
    sourceTitle: "Test signal: calm a parent reply before sending it",
    sourceType: "Founder Test",
    sourcePublisher: "Founder bootstrap",
    sourceDate: timestamp.slice(0, 10),
    sourceUrl: null,
    rawExcerpt:
      "I keep rewriting the email because I need to sound clear without making the parent feel attacked.",
    manualSummary:
      "Bootstrap signal for the founder happy path: teacher wants a calmer parent-reply message before pressing send.",
    signalCategory: null,
    severityScore: null,
    hookTemplateUsed: null,
    status: "New" as const,
  };
}

function assertSavedSignal(
  signal: Awaited<ReturnType<typeof saveSignalWithFallback>>["signal"],
  error: string | undefined,
  fallbackMessage: string,
) {
  if (!signal) {
    throw new Error(error ?? fallbackMessage);
  }

  return signal;
}

export async function createTestSignalReadyForApproval() {
  const timestamp = new Date().toISOString();
  const createdSignal = await createSignal(buildTestSignalCreatePayload(timestamp));
  const bootstrapScoring = await saveSignalWithFallback(createdSignal.recordId, {
    ingestionSource: "Founder bootstrap",
    ingestionMethod: "Create test signal",
    signalRelevanceScore: 8.9,
    signalNoveltyScore: 7.1,
    signalUrgencyScore: 7.8,
    brandFitScore: 9.2,
    sourceTrustScore: 8.4,
    keepRejectRecommendation: "Keep",
    whySelected:
      "Synthetic bootstrap signal for the empty-state founder path from interpretation through brief creation.",
    autoGenerated: false,
    needsHumanReview: false,
    qualityGateResult: "Pass",
    similarityToExistingContent: 12,
    reviewPriority: "High",
    teacherVoiceSource: "Founder Observation",
    scenarioAngle:
      "Replying to a frustrated parent without sounding defensive or escalating the tone.",
  });
  const scoredSignal = assertSavedSignal(
    bootstrapScoring.signal,
    bootstrapScoring.error,
    "Unable to prepare the test signal for interpretation.",
  );
  const interpretation = interpretSignal({
    recordId: scoredSignal.recordId,
    sourceTitle: scoredSignal.sourceTitle,
    sourceType: scoredSignal.sourceType,
    sourcePublisher: scoredSignal.sourcePublisher,
    sourceDate: scoredSignal.sourceDate,
    sourceUrl: scoredSignal.sourceUrl,
    rawExcerpt: scoredSignal.rawExcerpt,
    manualSummary: scoredSignal.manualSummary,
    scenarioAngle: scoredSignal.scenarioAngle,
  });
  const savedInterpretation = await saveSignalWithFallback(createdSignal.recordId, {
    ...interpretation,
    status: "Interpreted",
  });
  const interpretedSignal = assertSavedSignal(
    savedInterpretation.signal,
    savedInterpretation.error,
    "Unable to save interpretation on the test signal.",
  );
  const generationInput = toGenerationInputFromSignal(interpretedSignal);

  if (!generationInput) {
    throw new Error("Test signal interpretation did not produce a generation-ready payload.");
  }

  const generationRun = await generateDrafts(generationInput, {
    editorialMode: TEST_SIGNAL_EDITORIAL_MODE,
    founderVoiceMode: TEST_SIGNAL_FOUNDER_VOICE_MODE,
  });
  const reviewReadyAt = new Date().toISOString();
  const savedGeneration = await saveSignalWithFallback(createdSignal.recordId, {
    ...generationRun.outputs,
    editorialMode: TEST_SIGNAL_EDITORIAL_MODE,
    founderVoiceMode: TEST_SIGNAL_FOUNDER_VOICE_MODE,
    founderVoiceAppliedAt: reviewReadyAt,
    finalXDraft: generationRun.outputs.xDraft,
    finalLinkedInDraft: generationRun.outputs.linkedInDraft,
    finalRedditDraft: generationRun.outputs.redditDraft,
    xReviewStatus: "ready",
    linkedInReviewStatus: "ready",
    redditReviewStatus: "ready",
    finalReviewNotes:
      "Synthetic bootstrap signal prepared for approval from the founder empty-state flow.",
    finalReviewStartedAt: reviewReadyAt,
    finalReviewedAt: reviewReadyAt,
    status: "Reviewed",
  });
  const reviewReadySignal = assertSavedSignal(
    savedGeneration.signal,
    savedGeneration.error,
    "Unable to save generated drafts on the test signal.",
  );

  return {
    signal: reviewReadySignal,
    source: savedGeneration.source,
    persisted: savedGeneration.persisted,
  };
}
