import type { SignalRecord } from "@/types/signal";
import { normalizedSignalCandidateSchema, type IngestionFeedItem, type IngestionSourceDefinition, type NormalizedSignalCandidate } from "@/lib/ingestion/types";

function stripHtml(value: string | null): string | null {
  if (!value) {
    return null;
  }

  const withoutTags = value.replace(/<[^>]+>/g, " ");
  return withoutTags
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim() || null;
}

function truncate(value: string | null, maxLength: number): string | null {
  if (!value) {
    return null;
  }

  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength - 1).trim()}…`;
}

export function canonicalizeSourceUrl(value: string | null | undefined): string | null {
  if (!value) {
    return null;
  }

  try {
    const url = new URL(value);
    ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content", "fbclid", "gclid"].forEach((key) =>
      url.searchParams.delete(key),
    );
    url.hash = "";
    return url.toString();
  } catch {
    return value.trim() || null;
  }
}

export function buildDuplicateKeyFromSignal(signal: SignalRecord): string {
  const normalizedUrl = canonicalizeSourceUrl(signal.sourceUrl);
  if (normalizedUrl) {
    return `url:${normalizedUrl.toLowerCase()}`;
  }

  const title = signal.sourceTitle.trim().toLowerCase();
  const date = signal.sourceDate?.trim().toLowerCase() ?? "unknown";
  return `title-date:${title}|${date}`;
}

export function buildDuplicateKeyFromCandidate(candidate: Pick<NormalizedSignalCandidate, "sourceUrl" | "sourceTitle" | "sourceDate">): string {
  const normalizedUrl = canonicalizeSourceUrl(candidate.sourceUrl);
  if (normalizedUrl) {
    return `url:${normalizedUrl.toLowerCase()}`;
  }

  const title = candidate.sourceTitle.trim().toLowerCase();
  const date = candidate.sourceDate?.trim().toLowerCase() ?? "unknown";
  return `title-date:${title}|${date}`;
}

export function normalizeFeedItemToCandidate(
  source: IngestionSourceDefinition,
  item: IngestionFeedItem,
): NormalizedSignalCandidate | null {
  const sourceTitle = item.title?.trim();
  if (!sourceTitle) {
    return null;
  }

  const sourceUrl = canonicalizeSourceUrl(item.link);
  const rawExcerpt = truncate(stripHtml(item.excerpt ?? item.contentSnippet), 1000);
  const fallbackSummary =
    source.kind === "reddit"
      ? truncate(`Recent discussion in ${item.sourcePublisherOverride ?? source.name}: ${sourceTitle}`, 240)
      : null;
  const manualSummary = truncate(rawExcerpt, 240) ?? fallbackSummary;
  const sourceDate = item.publishedAt?.trim() || null;
  const sourceType = item.sourceTypeOverride?.trim() || (source.kind === "reddit" ? "Forum Post" : "Article");
  const sourcePublisher = item.sourcePublisherOverride?.trim() || source.publisher;
  const whySelected =
    item.whySelectedOverride?.trim() ||
    (source.kind === "reddit"
      ? "Imported from configured Reddit teacher discussion source for operator review."
      : `Imported from configured ${source.topic.toLowerCase()} feed for operator review.`);

  return normalizedSignalCandidateSchema.parse({
    sourceId: source.id,
    sourceName: source.name,
    sourceTitle,
    sourceUrl,
    sourceType,
    sourcePublisher,
    sourceDate,
    rawExcerpt,
    manualSummary,
    createdBy: "System Ingestion",
    status: "New",
    ingestionSource: source.name,
    ingestionMethod: source.kind === "reddit" ? "reddit" : source.kind.toUpperCase(),
    autoGenerated: true,
    needsHumanReview: true,
    keepRejectRecommendation: "Review",
    whySelected,
    reviewPriority: "Medium",
    duplicateKey: buildDuplicateKeyFromCandidate({
      sourceUrl,
      sourceTitle,
      sourceDate,
    }),
  });
}
