import { createSignal, listSignalsWithFallback } from "@/lib/airtable";
import { addMockSignalRecord } from "@/lib/mock-data";
import { buildMockRedditItems, fetchRedditPosts } from "@/lib/ingestion/fetch-reddit";
import { getEnabledIngestionSources, INGESTION_SOURCES } from "@/lib/ingestion/sources";
import { fetchSourceItems } from "@/lib/ingestion/fetch-feeds";
import { buildDuplicateKeyFromSignal, normalizeFeedItemToCandidate } from "@/lib/ingestion/normalize";
import { ingestionRunSummarySchema, type IngestionRunSummary, type IngestionSourceKind, type IngestionSourceResult } from "@/lib/ingestion/types";
import { getAppConfig } from "@/lib/config";

function createKindCounts() {
  return {
    rss: 0,
    atom: 0,
    json: 0,
    reddit: 0,
  };
}

function bumpKindCount(counts: ReturnType<typeof createKindCounts>, kind: IngestionSourceKind, amount = 1) {
  counts[kind] += amount;
}

export async function runIngestion(sourceIds?: string[]): Promise<{
  mode: "airtable" | "mock";
  result: IngestionRunSummary;
}> {
  const config = getAppConfig();
  const mode = config.isAirtableConfigured ? "airtable" : "mock";
  const enabledSources = getEnabledIngestionSources(sourceIds);
  const existing = await listSignalsWithFallback({ limit: 500 });
  const duplicateKeys = new Set(existing.signals.map(buildDuplicateKeyFromSignal));

  const sourceResults: IngestionSourceResult[] = [];
  const sourcesCheckedByKind = createKindCounts();
  const itemsFetchedByKind = createKindCounts();
  const itemsImportedByKind = createKindCounts();
  const itemsSkippedDuplicatesByKind = createKindCounts();
  let itemsFetched = 0;
  let itemsImported = 0;
  let itemsSkippedDuplicates = 0;

  for (const source of enabledSources) {
    bumpKindCount(sourcesCheckedByKind, source.kind);
    const sourceResult: IngestionSourceResult = {
      sourceId: source.id,
      sourceName: source.name,
      kind: source.kind,
      url: source.url,
      itemsFetched: 0,
      itemsImported: 0,
      itemsSkippedDuplicates: 0,
      errors: [],
    };

    try {
      let fetchedItems;

      try {
        fetchedItems = source.kind === "reddit" ? await fetchRedditPosts(source) : await fetchSourceItems(source);
      } catch (error) {
        if (mode === "mock" && source.kind === "reddit") {
          fetchedItems = buildMockRedditItems(source);
          sourceResult.errors.push("Live Reddit fetch unavailable. Using bounded mock Reddit posts.");
        } else {
          throw error;
        }
      }

      const items = fetchedItems.slice(0, source.maxItems ?? 25);
      sourceResult.itemsFetched = items.length;
      itemsFetched += items.length;
      bumpKindCount(itemsFetchedByKind, source.kind, items.length);

      for (const item of items) {
        const candidate = normalizeFeedItemToCandidate(source, item);
        if (!candidate) {
          continue;
        }

        if (duplicateKeys.has(candidate.duplicateKey)) {
          sourceResult.itemsSkippedDuplicates += 1;
          itemsSkippedDuplicates += 1;
          bumpKindCount(itemsSkippedDuplicatesByKind, source.kind);
          continue;
        }

        const payload = {
          createdBy: candidate.createdBy,
          sourceUrl: candidate.sourceUrl,
          sourceTitle: candidate.sourceTitle,
          sourceType: candidate.sourceType,
          sourcePublisher: candidate.sourcePublisher,
          sourceDate: candidate.sourceDate,
          rawExcerpt: candidate.rawExcerpt,
          manualSummary: candidate.manualSummary,
          signalCategory: null,
          severityScore: null,
          hookTemplateUsed: null,
          ingestionSource: candidate.ingestionSource,
          ingestionMethod: candidate.ingestionMethod,
          keepRejectRecommendation: candidate.keepRejectRecommendation,
          whySelected: candidate.whySelected,
          autoGenerated: candidate.autoGenerated,
          needsHumanReview: candidate.needsHumanReview,
          reviewPriority: candidate.reviewPriority,
          status: candidate.status,
        } as const;

        if (mode === "airtable") {
          await createSignal(payload);
        } else {
          addMockSignalRecord(payload);
        }

        duplicateKeys.add(candidate.duplicateKey);
        sourceResult.itemsImported += 1;
        itemsImported += 1;
        bumpKindCount(itemsImportedByKind, source.kind);
      }
    } catch (error) {
      sourceResult.errors.push(error instanceof Error ? error.message : "Unable to fetch source.");
    }

    sourceResults.push(sourceResult);
  }

  return {
    mode,
    result: ingestionRunSummarySchema.parse({
      configuredSourceCount: INGESTION_SOURCES.length,
      sourcesChecked: enabledSources.length,
      sourcesCheckedByKind,
      itemsFetched,
      itemsFetchedByKind,
      itemsImported,
      itemsImportedByKind,
      itemsSkippedDuplicates,
      itemsSkippedDuplicatesByKind,
      sourceResults,
      message:
        mode === "airtable"
          ? "Ingestion run completed against Airtable-backed signals."
          : "Ingestion run completed in mock mode. Imported records are session-local only.",
    }),
  };
}
