import { createSignal, listSignalsWithFallback } from "@/lib/airtable";
import { addMockSignalRecord } from "@/lib/mock-data";
import { getEnabledIngestionSources, INGESTION_SOURCES } from "@/lib/ingestion/sources";
import { fetchSourceItems } from "@/lib/ingestion/fetch-feeds";
import { buildDuplicateKeyFromSignal, normalizeFeedItemToCandidate } from "@/lib/ingestion/normalize";
import { ingestionRunSummarySchema, type IngestionRunSummary, type IngestionSourceResult } from "@/lib/ingestion/types";
import { getAppConfig } from "@/lib/config";

export async function runIngestion(sourceIds?: string[]): Promise<{
  mode: "airtable" | "mock";
  result: IngestionRunSummary;
}> {
  const config = getAppConfig();
  const mode = config.isAirtableConfigured ? "airtable" : "mock";
  const enabledSources = getEnabledIngestionSources(sourceIds);
  const existing = await listSignalsWithFallback({ limit: 500 });
  const duplicateKeys = new Set(existing.signals.map(buildDuplicateKeyFromSignal));

  const sourceResults: IngestionSourceResult[] = [];
  let itemsFetched = 0;
  let itemsImported = 0;
  let itemsSkippedDuplicates = 0;

  for (const source of enabledSources) {
    const sourceResult: IngestionSourceResult = {
      sourceId: source.id,
      sourceName: source.name,
      kind: source.kind,
      url: source.url,
      itemsFetched: 0,
      itemsImported: 0,
      itemsSkippedDuplicates: 0,
      errors: [],
    };

    try {
      const items = (await fetchSourceItems(source)).slice(0, source.maxItems ?? 25);
      sourceResult.itemsFetched = items.length;
      itemsFetched += items.length;

      for (const item of items) {
        const candidate = normalizeFeedItemToCandidate(source, item);
        if (!candidate) {
          continue;
        }

        if (duplicateKeys.has(candidate.duplicateKey)) {
          sourceResult.itemsSkippedDuplicates += 1;
          itemsSkippedDuplicates += 1;
          continue;
        }

        const payload = {
          createdBy: candidate.createdBy,
          sourceUrl: candidate.sourceUrl,
          sourceTitle: candidate.sourceTitle,
          sourceType: candidate.sourceType,
          sourcePublisher: candidate.sourcePublisher,
          sourceDate: candidate.sourceDate,
          rawExcerpt: candidate.rawExcerpt,
          manualSummary: candidate.manualSummary,
          signalCategory: null,
          severityScore: null,
          hookTemplateUsed: null,
          ingestionSource: candidate.ingestionSource,
          ingestionMethod: candidate.ingestionMethod,
          keepRejectRecommendation: candidate.keepRejectRecommendation,
          whySelected: candidate.whySelected,
          autoGenerated: candidate.autoGenerated,
          needsHumanReview: candidate.needsHumanReview,
          reviewPriority: candidate.reviewPriority,
          status: candidate.status,
        } as const;

        if (mode === "airtable") {
          await createSignal(payload);
        } else {
          addMockSignalRecord(payload);
        }

        duplicateKeys.add(candidate.duplicateKey);
        sourceResult.itemsImported += 1;
        itemsImported += 1;
      }
    } catch (error) {
      sourceResult.errors.push(error instanceof Error ? error.message : "Unable to fetch source.");
    }

    sourceResults.push(sourceResult);
  }

  return {
    mode,
    result: ingestionRunSummarySchema.parse({
      configuredSourceCount: INGESTION_SOURCES.length,
      sourcesChecked: enabledSources.length,
      itemsFetched,
      itemsImported,
      itemsSkippedDuplicates,
      sourceResults,
      message:
        mode === "airtable"
          ? "Ingestion run completed against Airtable-backed signals."
          : "Ingestion run completed in mock mode. Imported records are session-local only.",
    }),
  };
}
