import { z } from "zod";

export const INGESTION_SOURCE_KINDS = ["rss", "atom", "json", "reddit", "query"] as const;
export const INGESTION_SOURCE_PRIORITIES = ["low", "normal", "high"] as const;

export type IngestionSourceKind = (typeof INGESTION_SOURCE_KINDS)[number];
export type IngestionSourcePriority = (typeof INGESTION_SOURCE_PRIORITIES)[number];

export const ingestionKindCountSchema = z.object({
  rss: z.number().int().nonnegative(),
  atom: z.number().int().nonnegative(),
  json: z.number().int().nonnegative(),
  reddit: z.number().int().nonnegative(),
  query: z.number().int().nonnegative(),
});

export const ingestionSourceSchema = z
  .object({
    id: z.string().trim().min(1),
    name: z.string().trim().min(1),
    kind: z.enum(INGESTION_SOURCE_KINDS),
    url: z.string().trim().url(),
    subreddit: z.string().trim().min(1).optional(),
    query: z.string().trim().min(1).optional(),
    provider: z.string().trim().min(1).optional(),
    publisher: z.string().trim().min(1),
    topic: z.string().trim().min(1),
    enabled: z.boolean(),
    maxItemsPerRun: z.number().int().positive().max(100),
    priority: z.enum(INGESTION_SOURCE_PRIORITIES).default("normal"),
    notes: z.string().trim().optional(),
  })
  .superRefine((value, context) => {
    if (value.kind === "reddit" && !value.subreddit) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["subreddit"],
        message: "Reddit sources require a subreddit reference.",
      });
    }

    if (value.kind === "query" && !value.query) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["query"],
        message: "Query sources require explicit query text.",
      });
    }
  });

export type IngestionSourceDefinition = z.infer<typeof ingestionSourceSchema>;

export const ingestionSourceOverrideSchema = z.object({
  id: z.string().trim().min(1),
  enabled: z.boolean().optional(),
  maxItemsPerRun: z.number().int().positive().max(100).optional(),
  priority: z.enum(INGESTION_SOURCE_PRIORITIES).optional(),
  notes: z.string().trim().optional(),
});

export type IngestionSourceOverride = z.infer<typeof ingestionSourceOverrideSchema>;

export const ingestionFeedItemSchema = z.object({
  externalId: z.string().trim().min(1).nullable(),
  title: z.string().trim().min(1).nullable(),
  link: z.string().trim().nullable(),
  publishedAt: z.string().trim().nullable(),
  excerpt: z.string().trim().nullable(),
  contentSnippet: z.string().trim().nullable(),
  sourceTypeOverride: z.string().trim().min(1).nullable().optional(),
  sourcePublisherOverride: z.string().trim().min(1).nullable().optional(),
  whySelectedOverride: z.string().trim().min(1).nullable().optional(),
});

export type IngestionFeedItem = z.infer<typeof ingestionFeedItemSchema>;

export const normalizedSignalCandidateSchema = z.object({
  sourceId: z.string().trim().min(1),
  sourceName: z.string().trim().min(1),
  sourceTitle: z.string().trim().min(1),
  sourceUrl: z.string().trim().nullable(),
  sourceType: z.string().trim().min(1),
  sourcePublisher: z.string().trim().nullable(),
  sourceDate: z.string().trim().nullable(),
  rawExcerpt: z.string().trim().nullable(),
  manualSummary: z.string().trim().nullable(),
  createdBy: z.literal("System Ingestion"),
  status: z.literal("New"),
  ingestionSource: z.string().trim().min(1),
  ingestionMethod: z.string().trim().min(1),
  autoGenerated: z.literal(true),
  needsHumanReview: z.literal(true),
  keepRejectRecommendation: z.literal("Review"),
  whySelected: z.string().trim().min(1),
  reviewPriority: z.literal("Medium"),
  duplicateKey: z.string().trim().min(1),
});

export type NormalizedSignalCandidate = z.infer<typeof normalizedSignalCandidateSchema>;

export const ingestionSourceResultSchema = z.object({
  sourceId: z.string().trim().min(1),
  sourceName: z.string().trim().min(1),
  kind: z.enum(INGESTION_SOURCE_KINDS),
  url: z.string().trim().url(),
  maxItemsPerRun: z.number().int().positive(),
  itemsFetched: z.number().int().nonnegative(),
  itemsImported: z.number().int().nonnegative(),
  itemsSkipped: z.number().int().nonnegative(),
  itemsSkippedDuplicates: z.number().int().nonnegative(),
  errors: z.array(z.string()),
});

export type IngestionSourceResult = z.infer<typeof ingestionSourceResultSchema>;

export const ingestionSourcePerformanceSchema = z.object({
  totalSignals: z.number().int().nonnegative(),
  keepSignals: z.number().int().nonnegative(),
  reviewSignals: z.number().int().nonnegative(),
  rejectedSignals: z.number().int().nonnegative(),
  approvedSignals: z.number().int().nonnegative(),
  usefulSignals: z.number().int().nonnegative(),
  interpretedSignals: z.number().int().nonnegative(),
  generatedSignals: z.number().int().nonnegative(),
  postedSignals: z.number().int().nonnegative(),
  strongOutcomeSignals: z.number().int().nonnegative(),
  acceptableOutcomeSignals: z.number().int().nonnegative(),
  weakOutcomeSignals: z.number().int().nonnegative(),
  approvalRate: z.number().min(0).max(1),
  rejectionRate: z.number().min(0).max(1),
  usefulnessRate: z.number().min(0).max(1),
  averageOutcomeScore: z.number().min(-3).max(3).nullable(),
});

export type IngestionSourcePerformance = z.infer<typeof ingestionSourcePerformanceSchema>;

export const ingestionSourceRecommendationSchema = z.object({
  action: z.enum(["reduce_source_weight", "pause_source", "refine_query"]),
  summary: z.string().trim().min(1),
  rationale: z.string().trim().min(1),
});

export type IngestionSourceRecommendation = z.infer<typeof ingestionSourceRecommendationSchema>;

export const managedIngestionSourceSchema = ingestionSourceSchema.extend({
  ingestionLabel: z.string().trim().min(1),
  performance: ingestionSourcePerformanceSchema,
  recommendations: z.array(ingestionSourceRecommendationSchema).max(3).default([]),
});

export type ManagedIngestionSource = z.infer<typeof managedIngestionSourceSchema>;

export const ingestionRunSummarySchema = z.object({
  configuredSourceCount: z.number().int().nonnegative(),
  sourcesChecked: z.number().int().nonnegative(),
  sourcesCheckedByKind: ingestionKindCountSchema,
  itemsFetched: z.number().int().nonnegative(),
  itemsFetchedByKind: ingestionKindCountSchema,
  itemsImported: z.number().int().nonnegative(),
  itemsImportedByKind: ingestionKindCountSchema,
  itemsSkipped: z.number().int().nonnegative(),
  itemsSkippedByKind: ingestionKindCountSchema,
  itemsSkippedDuplicates: z.number().int().nonnegative(),
  itemsSkippedDuplicatesByKind: ingestionKindCountSchema,
  sourceResults: z.array(ingestionSourceResultSchema),
  message: z.string().trim().min(1),
});

export type IngestionRunSummary = z.infer<typeof ingestionRunSummarySchema>;
