import { z } from "zod";

export const INGESTION_SOURCE_KINDS = ["rss", "atom", "json"] as const;

export type IngestionSourceKind = (typeof INGESTION_SOURCE_KINDS)[number];

export const ingestionSourceSchema = z.object({
  id: z.string().trim().min(1),
  name: z.string().trim().min(1),
  kind: z.enum(INGESTION_SOURCE_KINDS),
  url: z.string().trim().url(),
  publisher: z.string().trim().min(1),
  topic: z.string().trim().min(1),
  enabled: z.boolean(),
  maxItems: z.number().int().positive().max(100).optional(),
  notes: z.string().trim().optional(),
});

export type IngestionSourceDefinition = z.infer<typeof ingestionSourceSchema>;

export const ingestionFeedItemSchema = z.object({
  externalId: z.string().trim().min(1).nullable(),
  title: z.string().trim().min(1).nullable(),
  link: z.string().trim().nullable(),
  publishedAt: z.string().trim().nullable(),
  excerpt: z.string().trim().nullable(),
  contentSnippet: z.string().trim().nullable(),
});

export type IngestionFeedItem = z.infer<typeof ingestionFeedItemSchema>;

export const normalizedSignalCandidateSchema = z.object({
  sourceId: z.string().trim().min(1),
  sourceName: z.string().trim().min(1),
  sourceTitle: z.string().trim().min(1),
  sourceUrl: z.string().trim().nullable(),
  sourceType: z.string().trim().min(1),
  sourcePublisher: z.string().trim().nullable(),
  sourceDate: z.string().trim().nullable(),
  rawExcerpt: z.string().trim().nullable(),
  manualSummary: z.string().trim().nullable(),
  createdBy: z.literal("System Ingestion"),
  status: z.literal("New"),
  ingestionSource: z.string().trim().min(1),
  ingestionMethod: z.string().trim().min(1),
  autoGenerated: z.literal(true),
  needsHumanReview: z.literal(true),
  keepRejectRecommendation: z.literal("Review"),
  whySelected: z.string().trim().min(1),
  reviewPriority: z.literal("Medium"),
  duplicateKey: z.string().trim().min(1),
});

export type NormalizedSignalCandidate = z.infer<typeof normalizedSignalCandidateSchema>;

export const ingestionSourceResultSchema = z.object({
  sourceId: z.string().trim().min(1),
  sourceName: z.string().trim().min(1),
  kind: z.enum(INGESTION_SOURCE_KINDS),
  url: z.string().trim().url(),
  itemsFetched: z.number().int().nonnegative(),
  itemsImported: z.number().int().nonnegative(),
  itemsSkippedDuplicates: z.number().int().nonnegative(),
  errors: z.array(z.string()),
});

export type IngestionSourceResult = z.infer<typeof ingestionSourceResultSchema>;

export const ingestionRunSummarySchema = z.object({
  configuredSourceCount: z.number().int().nonnegative(),
  sourcesChecked: z.number().int().nonnegative(),
  itemsFetched: z.number().int().nonnegative(),
  itemsImported: z.number().int().nonnegative(),
  itemsSkippedDuplicates: z.number().int().nonnegative(),
  sourceResults: z.array(ingestionSourceResultSchema),
  message: z.string().trim().min(1),
});

export type IngestionRunSummary = z.infer<typeof ingestionRunSummarySchema>;
